/**
 * MVEE Song Catalogue — Cosmic ambient soundtrack
 *
 * Style: otherworldly, vast, contemplative. Think Outer Wilds, FTL,
 * or Dwarf Fortress ambient. Not fantasy-medieval like Creatures.
 *
 * Filenames must match audio files generated by MUL-3159 and deployed
 * to /audio/mvee/ on the play site.
 */

import type { SongEntry } from '../lore/SongSystem.js';

export const MVEE_SONG_CATALOGUE: readonly SongEntry[] = [
  // Ambient — exploration, idle (4 tracks)
  { filename: 'void-drift.mp3', occasion: 'ambient' },
  { filename: 'stellar-murmur.mp3', occasion: 'ambient' },
  { filename: 'deep-field.mp3', occasion: 'ambient' },
  { filename: 'lattice-hum.mp3', occasion: 'ambient' },

  // Grief — death events (2 tracks)
  { filename: 'echo-of-names.mp3', occasion: 'grief' },
  { filename: 'last-signal.mp3', occasion: 'grief' },

  // Elder — age milestones, wisdom (2 tracks)
  { filename: 'ancient-light.mp3', occasion: 'elder' },
  { filename: 'convergence.mp3', occasion: 'elder' },

  // Warning — danger, combat (1 track)
  { filename: 'red-shift.mp3', occasion: 'warning' },

  // Hearth — social, village scenes (1 track)
  { filename: 'hearthglow.mp3', occasion: 'hearth' },

  // Birth — new life (1 track)
  { filename: 'first-breath.mp3', occasion: 'birth' },
] as const;
