/**
 * World and time-related events.
 * Covers world lifecycle, time progression, and checkpoints.
 */
import type { EntityId } from '../../types.js';

/**
 * World and time events.
 */
export interface WorldEvents {
  // === World & Time Events ===
  'world:tick:start': { tick: number };
  'world:tick:end': { tick: number };
  'world:loaded': { tick: number; entityCount: number };  // Emitted after world state is restored from save
  'world:time:hour': { hour: number; day: number };
  'world:time:day': { day: number; season: string };
  'world:time:season': { season: string; year: number };
  'world:time:year': { year: number };

  // === Time Compression Events (Grand Strategy) ===
  'time:scale_changed': {
    oldScale: number;
    newScale: number;
    tier: string;
  };
  'time:jump_started': {
    startTick: number;
    targetTick: number;
    years: number;
  };
  'time:jump_completed': {
    startTick: number;
    endTick: number;
    years: number;
  };
  'time:era_changed': {
    era: number;
    previousEra: number;
    tick: number;
  };
  'time:simulation_mode_changed': {
    mode: 'ecs' | 'statistical';
    timeScale: number;
  };
  'time:era_snapshot_created': {
    eraNumber: number;
    eraName: string;
    yearsCovered: number;
    soulCount: number;
  };
  'time:throttles_updated': {
    timeScale: number;
    previousScale: number;
    throttledSystems: string[];
    disabledSystems: string[];
  };

  // === Statistical Mode Events ===
  'time:entered_statistical_mode': {
    entitiesPreserved: number;
    soulAgents: number;
    tick: number;
  };
  'time:exited_statistical_mode': {
    entitiesRestored: number;
    soulAgentsResumed: number;
    tick: number;
  };
  'time:entity_preserved': {
    entityId: EntityId;
    componentsPreserved: number;
  };
  'time:entity_restored': {
    entityId: EntityId;
    componentsRestored: number;
  };

  // === Time Events ===
  'time:day_changed': {
    day: number;
    newDay?: number;
  };
  'time:phase_changed': {
    phase: string;
    newPhase?: string;
    oldPhase?: string;
  };
  'time:new_week': {
    week: number;
    day?: number;
    agentId?: EntityId;
    timestamp?: number;
  };
  'time:season_change': {
    newSeason: string;
    oldSeason?: string;
    agentId?: EntityId;
    timestamp?: number;
  };

  // === Checkpoint Events (Time Travel) ===
  /** Automatic checkpoint created at midnight */
  'checkpoint:created': {
    checkpoint: {
      key: string;
      name: string;
      day: number;
      tick: number;
      timestamp: number;
      universeId: string;
      magicLawsHash: string;
    };
  };

  /** Request LLM to generate checkpoint name */
  'checkpoint:name_request': {
    checkpoint: {
      key: string;
      name: string;
      day: number;
      tick: number;
      timestamp: number;
      universeId: string;
      magicLawsHash: string;
    };
  };

  /** Checkpoint name generated by LLM */
  'checkpoint:named': {
    checkpointKey: string;
    oldName: string;
    newName: string;
  };

  // EXOTIC PLOT EVENTS - for Fates Council
  /** When time manipulation creates a paradox */
  'time:paradox_detected': {
    agentId: EntityId;  // Who caused the paradox
    soulId: string;
    paradoxType: 'grandfather' | 'causal_loop' | 'bootstrap' | 'ontological';
    timelineId: string;
    alterationMagnitude: number;  // How big was the change (0-1)
    affectedSouls: string[];  // Other souls impacted
    tick: number;
  };
}

/**
 * Union of all world event types.
 */
export type WorldEventType = keyof WorldEvents;

/**
 * Union of all world event data payloads.
 */
export type WorldEventData = WorldEvents[WorldEventType];
