/**
 * Creature Defensive Systems
 *
 * How alien creatures protect themselves from harm.
 * Because survival demands creativity, especially in hostile universes.
 */

export interface DefensiveSystem {
  name: string;
  mechanism: string;
  effectiveness: 'poor' | 'moderate' | 'good' | 'excellent' | 'overkill';
  activationType: 'passive' | 'reactive' | 'preemptive';
  energyCost: 'minimal' | 'low' | 'moderate' | 'high' | 'extreme';
  limitations: string[];
  flavorText: string;
}

export const DEFENSIVE_SYSTEMS: Record<string, DefensiveSystem> = {
  'armored_shell': {
    name: 'Heavy Armor Plating',
    mechanism: 'Thick protective exterior deflects attacks',
    effectiveness: 'good',
    activationType: 'passive',
    energyCost: 'minimal',
    limitations: ['Heavy', 'Slow movement', 'Inflexible'],
    flavorText: 'Hard shell. Thick. Attacks bounce. Movement slow. Protection constant.',
  },
  'camouflage': {
    name: 'Adaptive Camouflage',
    mechanism: 'Skin changes color to match environment',
    effectiveness: 'good',
    activationType: 'reactive',
    energyCost: 'low',
    limitations: ['Motion reveals', 'Close inspection fails', 'Pattern matching'],
    flavorText: 'Blend in. Match surroundings. Invisible. Mostly. Movement betrays.',
  },
  'toxic_secretion': {
    name: 'Poison Glands',
    mechanism: 'Secretes toxins that harm attackers',
    effectiveness: 'excellent',
    activationType: 'reactive',
    energyCost: 'moderate',
    limitations: ['Immune predators', 'Depletion possible', 'Self-harm risk'],
    flavorText: 'Touch hurts. Bite kills. Predators learn. Survivors warn others. Effective.',
  },
  'regeneration': {
    name: 'Rapid Healing',
    mechanism: 'Wounds close and regrow tissue quickly',
    effectiveness: 'excellent',
    activationType: 'reactive',
    energyCost: 'high',
    limitations: ['Energy intensive', 'Vital damage still fatal', 'Slow for major wounds'],
    flavorText: 'Heal fast. Regrow limbs. Damage temporary. Energy costly. Survival high.',
  },
  'teleportation_escape': {
    name: 'Instant Relocation',
    mechanism: 'Disappears and reappears elsewhere when threatened',
    effectiveness: 'excellent',
    activationType: 'reactive',
    energyCost: 'extreme',
    limitations: ['Exhausting', 'Limited range', 'Cooldown required'],
    flavorText: 'Danger sensed. Vanish. Appear elsewhere. Safe. Exhausted. Repeat if necessary.',
  },
  'electrical_discharge': {
    name: 'Shock Defense',
    mechanism: 'Releases powerful electrical current',
    effectiveness: 'excellent',
    activationType: 'reactive',
    energyCost: 'high',
    limitations: ['Insulated attackers', 'Water required', 'Self-shock possible'],
    flavorText: 'Attacked. Shock released. Attacker zapped. Effective. Water helps. Dry less so.',
  },
  'spiny_protrusions': {
    name: 'Defensive Spikes',
    mechanism: 'Sharp spines deter physical contact',
    effectiveness: 'moderate',
    activationType: 'passive',
    energyCost: 'minimal',
    limitations: ['Ranged attacks unaffected', 'Grooming difficult', 'Accidental injuries'],
    flavorText: 'Spikes everywhere. Touch painful. Hug impossible. Effective. Lonely.',
  },
  'ink_cloud': {
    name: 'Obscuring Emission',
    mechanism: 'Releases dark cloud to obscure vision and escape',
    effectiveness: 'moderate',
    activationType: 'reactive',
    energyCost: 'low',
    limitations: ['Open areas less effective', 'Depletion', 'Non-visual predators'],
    flavorText: 'Release cloud. Vision obscured. Escape. Works. Sometimes. Predators confused.',
  },
  'phase_shifting': {
    name: 'Matter Intangibility',
    mechanism: 'Shifts out of phase with normal matter',
    effectiveness: 'overkill',
    activationType: 'preemptive',
    energyCost: 'extreme',
    limitations: ['Can\'t interact while phased', 'Energy intensive', 'Temporal instability'],
    flavorText: 'Become intangible. Attacks pass through. Untouchable. Also can\'t touch. Trade-off.',
  },
  'sonic_scream': {
    name: 'Acoustic Weapon',
    mechanism: 'Emits deafening or disorienting sound waves',
    effectiveness: 'good',
    activationType: 'reactive',
    energyCost: 'moderate',
    limitations: ['Deaf predators', 'Self-damage risk', 'Ear protection needed'],
    flavorText: 'Scream loud. Very loud. Attackers flee. Ears hurt. Everyone\'s ears. Effective.',
  },
  'temporal_displacement': {
    name: 'Time Dodge',
    mechanism: 'Skips forward in time to avoid attack',
    effectiveness: 'excellent',
    activationType: 'reactive',
    energyCost: 'extreme',
    limitations: ['Paradoxes', 'Reappears in same danger', 'Confusing'],
    flavorText: 'Attack comes. Jump forward. Miss attack. Temporal headache. Alive though.',
  },
  'energy_shield': {
    name: 'Force Field',
    mechanism: 'Generates protective energy barrier',
    effectiveness: 'excellent',
    activationType: 'preemptive',
    energyCost: 'high',
    limitations: ['Sustained drain', 'Can be overwhelmed', 'Blocks everything'],
    flavorText: 'Shield up. Energy barrier. Attacks repelled. Constant drain. Worth it.',
  },
  'mimicry': {
    name: 'Predator Mimicry',
    mechanism: 'Resembles dangerous species',
    effectiveness: 'moderate',
    activationType: 'passive',
    energyCost: 'minimal',
    limitations: ['Knowledgeable predators', 'Must maintain appearance', 'Model species needed'],
    flavorText: 'Look dangerous. Not dangerous. Predators fooled. Usually. Bluff works.',
  },
  'dimension_hop': {
    name: 'Reality Shifting',
    mechanism: 'Steps into parallel dimension briefly',
    effectiveness: 'excellent',
    activationType: 'reactive',
    energyCost: 'extreme',
    limitations: ['Other dimension may be worse', 'Limited duration', 'Disorienting'],
    flavorText: 'Step sideways. Different reality. Briefly. Danger avoided. Return. Maybe worse.',
  },
  'reflective_surface': {
    name: 'Mirror Coating',
    mechanism: 'Reflects attacks back at attacker',
    effectiveness: 'good',
    activationType: 'passive',
    energyCost: 'low',
    limitations: ['Physical attacks penetrate', 'Maintenance required', 'Angle dependent'],
    flavorText: 'Mirrored. Attacks reflect. Energy back. Physical different. Shiny defense.',
  },
  'swarm_dispersal': {
    name: 'Fragment Escape',
    mechanism: 'Breaks into many small pieces to escape',
    effectiveness: 'good',
    activationType: 'reactive',
    energyCost: 'moderate',
    limitations: ['Reassembly needed', 'Vulnerable pieces', 'Identity questions'],
    flavorText: 'Break apart. Scatter. Pieces flee. Regroup later. Confusing. Effective.',
  },
  'probability_alteration': {
    name: 'Luck Manipulation',
    mechanism: 'Makes attacks less likely to succeed',
    effectiveness: 'excellent',
    activationType: 'preemptive',
    energyCost: 'high',
    limitations: ['Not foolproof', 'Entropy cost', 'Luck depletes'],
    flavorText: 'Make luck. Attacks miss. Probability bent. Eventually fails. Usually works.',
  },
  'death_feigning': {
    name: 'Play Dead',
    mechanism: 'Convincingly appears deceased',
    effectiveness: 'moderate',
    activationType: 'reactive',
    energyCost: 'minimal',
    limitations: ['Scavengers still eat', 'Must remain still', 'Not all predators fooled'],
    flavorText: 'Fall down. Look dead. Predator leaves. Wait. Escape. Works sometimes.',
  },
  'quantum_uncertainty': {
    name: 'Superposition Defense',
    mechanism: 'Exists in multiple locations simultaneously',
    effectiveness: 'overkill',
    activationType: 'preemptive',
    energyCost: 'extreme',
    limitations: ['Observation collapses', 'Confusing', 'Energy intensive'],
    flavorText: 'Be everywhere. And nowhere. Attack hits wrong you. Quantum confusion. Safe.',
  },
  'emotional_manipulation': {
    name: 'Empathic Pacification',
    mechanism: 'Projects calming emotions to predators',
    effectiveness: 'moderate',
    activationType: 'reactive',
    energyCost: 'moderate',
    limitations: ['Non-emotional predators', 'Strong will resists', 'Temporary'],
    flavorText: 'Project calm. Predator peaceful. Attack forgotten. Briefly. Escape window.',
  },
  'hardlight_clone': {
    name: 'Decoy Projection',
    mechanism: 'Creates solid light duplicates',
    effectiveness: 'good',
    activationType: 'reactive',
    energyCost: 'high',
    limitations: ['Limited duration', 'Energy signature', 'Smart predators learn'],
    flavorText: 'Make copies. Light-based. Solid. Predator attacks wrong one. Escape.',
  },
  'gravity_well': {
    name: 'Mass Increase',
    mechanism: 'Increases local gravity around self',
    effectiveness: 'good',
    activationType: 'reactive',
    energyCost: 'high',
    limitations: ['Slows self too', 'Range limited', 'Energy drain'],
    flavorText: 'Increase gravity. Attackers slowed. Self slowed. Heavy defense. Escape hard.',
  },
  'crystal_armor': {
    name: 'Crystalline Growth',
    mechanism: 'Rapidly grows protective crystal layer',
    effectiveness: 'excellent',
    activationType: 'reactive',
    energyCost: 'moderate',
    limitations: ['Brittle', 'Shatter risk', 'Movement restricted'],
    flavorText: 'Crystals grow. Cover body. Hard protection. Beautiful. Fragile. Shatters dramatically.',
  },
  'molecular_restructure': {
    name: 'Form Shifting',
    mechanism: 'Changes molecular structure when threatened',
    effectiveness: 'excellent',
    activationType: 'reactive',
    energyCost: 'extreme',
    limitations: ['Identity blur', 'Energy intensive', 'Painful transformation'],
    flavorText: 'Change form. Molecules rearrange. New shape. Attack ineffective. Painful. Alive.',
  },
  'void_absorption': {
    name: 'Entropy Shield',
    mechanism: 'Absorbs attacks into void dimension',
    effectiveness: 'overkill',
    activationType: 'preemptive',
    energyCost: 'extreme',
    limitations: ['Void contamination', 'Reality weakening', 'Dangerous'],
    flavorText: 'Open void. Attacks absorbed. Gone. Forever. Void leaks back. Concerning.',
  },
};
