/**
 * Creature Intelligence Levels
 *
 * Cognitive capabilities and thinking patterns of alien creatures.
 * Because intelligence manifests in countless unexpected forms.
 */

export interface IntelligenceLevel {
  name: string;
  cognitiveAbilities: string[];
  problemSolving: 'none' | 'basic' | 'moderate' | 'advanced' | 'transcendent';
  selfAwareness: 'none' | 'minimal' | 'moderate' | 'full' | 'beyond';
  communication: string;
  learningCapacity: 'none' | 'instinct_only' | 'slow' | 'fast' | 'instant' | 'precognitive';
  flavorText: string;
}

export const INTELLIGENCE_LEVELS: Record<string, IntelligenceLevel> = {
  'instinctual': {
    name: 'Pure Instinct',
    cognitiveAbilities: ['Pattern recognition', 'Basic stimulus response', 'Survival behaviors'],
    problemSolving: 'none',
    selfAwareness: 'none',
    communication: 'Chemical signals, basic sounds',
    learningCapacity: 'instinct_only',
    flavorText: 'React. No thought. Instinct guides. Survive. Reproduce. Simple. Effective.',
  },
  'simple_learning': {
    name: 'Basic Cognition',
    cognitiveAbilities: ['Trial and error', 'Simple memory', 'Cause and effect'],
    problemSolving: 'basic',
    selfAwareness: 'minimal',
    communication: 'Limited signals, simple calls',
    learningCapacity: 'slow',
    flavorText: 'Learn slowly. Remember some. Adapt slightly. Better than instinct. Not much.',
  },
  'tool_user': {
    name: 'Practical Intelligence',
    cognitiveAbilities: ['Tool use', 'Planning', 'Object manipulation', 'Social learning'],
    problemSolving: 'moderate',
    selfAwareness: 'minimal',
    communication: 'Complex vocalizations, gestures',
    learningCapacity: 'fast',
    flavorText: 'Use tools. Solve problems. Plan ahead. Think. Act. Improve. Smart enough.',
  },
  'self_aware': {
    name: 'Conscious Being',
    cognitiveAbilities: ['Self-recognition', 'Abstract thought', 'Future planning', 'Empathy'],
    problemSolving: 'advanced',
    selfAwareness: 'full',
    communication: 'Language, symbolic thought',
    learningCapacity: 'fast',
    flavorText: 'Know self. Think abstractly. Plan far. Feel others. Conscious. Aware. Troubled.',
  },
  'hive_intelligence': {
    name: 'Distributed Mind',
    cognitiveAbilities: ['Collective thinking', 'Parallel processing', 'Shared memory', 'Coordinated action'],
    problemSolving: 'advanced',
    selfAwareness: 'moderate',
    communication: 'Telepathic network, instant sharing',
    learningCapacity: 'fast',
    flavorText: 'Think together. Many minds. One thought. Individual unclear. Collective smart.',
  },
  'telepathic': {
    name: 'Mental Communication',
    cognitiveAbilities: ['Mind reading', 'Thought projection', 'Mental imagery', 'Empathic sensing'],
    problemSolving: 'advanced',
    selfAwareness: 'full',
    communication: 'Direct thought transfer',
    learningCapacity: 'instant',
    flavorText: 'Read minds. Share thoughts. Perfect understanding. No privacy. Total communication.',
  },
  'precognitive': {
    name: 'Future Sight',
    cognitiveAbilities: ['Probability prediction', 'Future glimpses', 'Timeline awareness', 'Causal understanding'],
    problemSolving: 'transcendent',
    selfAwareness: 'full',
    communication: 'Temporal messaging, prediction sharing',
    learningCapacity: 'precognitive',
    flavorText: 'See futures. Multiple timelines. Choose best. Know outcomes. Already learned.',
  },
  'quantum_mind': {
    name: 'Superposition Thinking',
    cognitiveAbilities: ['Simultaneous thoughts', 'Probability collapse', 'Quantum computation', 'Wave function manipulation'],
    problemSolving: 'transcendent',
    selfAwareness: 'beyond',
    communication: 'Quantum entanglement',
    learningCapacity: 'instant',
    flavorText: 'Think all thoughts. Simultaneously. Collapse to answer. Quantum cognition. Incomprehensible.',
  },
  'emotional_only': {
    name: 'Pure Feeling',
    cognitiveAbilities: ['Emotional intelligence', 'Mood detection', 'Empathic response', 'Feeling-based decisions'],
    problemSolving: 'basic',
    selfAwareness: 'moderate',
    communication: 'Emotional broadcasting',
    learningCapacity: 'slow',
    flavorText: 'Feel everything. Think nothing. Emotions guide. Logic absent. Empathy perfect.',
  },
  'mathematical_genius': {
    name: 'Pure Logic',
    cognitiveAbilities: ['Perfect calculation', 'Pattern analysis', 'Mathematical modeling', 'Logical deduction'],
    problemSolving: 'transcendent',
    selfAwareness: 'minimal',
    communication: 'Mathematical language',
    learningCapacity: 'instant',
    flavorText: 'Calculate. Deduce. Logic perfect. Emotions absent. Math solves all. Supposedly.',
  },
  'artistic_savant': {
    name: 'Creative Genius',
    cognitiveAbilities: ['Artistic vision', 'Pattern creation', 'Aesthetic judgment', 'Innovation'],
    problemSolving: 'moderate',
    selfAwareness: 'full',
    communication: 'Artistic expression, metaphor',
    learningCapacity: 'fast',
    flavorText: 'Create beauty. See patterns. Make art. Practical problems harder. Beauty easier.',
  },
  'dream_logic': {
    name: 'Oneiric Thinking',
    cognitiveAbilities: ['Symbolic reasoning', 'Metaphorical thought', 'Surreal connections', 'Dream interpretation'],
    problemSolving: 'moderate',
    selfAwareness: 'moderate',
    communication: 'Dream sharing, symbolism',
    learningCapacity: 'slow',
    flavorText: 'Think in dreams. Logic fluid. Symbols meaningful. Reality optional. Makes sense. Somehow.',
  },
  'genetic_memory': {
    name: 'Ancestral Knowledge',
    cognitiveAbilities: ['Inherited memories', 'Species knowledge', 'Instinct plus learning', 'Collective history'],
    problemSolving: 'advanced',
    selfAwareness: 'moderate',
    communication: 'Memory sharing, genetic signals',
    learningCapacity: 'precognitive',
    flavorText: 'Remember ancestors. Born knowing. Species wisdom. Individual plus collective. Never start from zero.',
  },
  'swarm_emergent': {
    name: 'Collective Emergence',
    cognitiveAbilities: ['Emergent patterns', 'Distributed decision-making', 'Adaptive behavior', 'No central control'],
    problemSolving: 'advanced',
    selfAwareness: 'none',
    communication: 'Local interactions only',
    learningCapacity: 'fast',
    flavorText: 'Intelligence emerges. No individual smart. Collective brilliant. How? Unknown. Works anyway.',
  },
  'dimensional_awareness': {
    name: 'Hyperspace Cognition',
    cognitiveAbilities: ['Extra-dimensional perception', 'Higher geometry', 'Multidimensional thinking', 'Space folding'],
    problemSolving: 'transcendent',
    selfAwareness: 'beyond',
    communication: 'Hyperdimensional signals',
    learningCapacity: 'instant',
    flavorText: 'Think in higher dimensions. See beyond three. Understand space differently. Explain impossible.',
  },
  'time_aware': {
    name: 'Temporal Consciousness',
    cognitiveAbilities: ['Past/future awareness', 'Timeline manipulation', 'Causal understanding', 'Temporal navigation'],
    problemSolving: 'transcendent',
    selfAwareness: 'beyond',
    communication: 'Temporal messages',
    learningCapacity: 'precognitive',
    flavorText: 'Experience all time. See past. Know future. Present unclear. Learn before happening.',
  },
  'crystalline_logic': {
    name: 'Mineral Thought',
    cognitiveAbilities: ['Lattice computation', 'Resonance thinking', 'Slow precision', 'Perfect memory'],
    problemSolving: 'advanced',
    selfAwareness: 'full',
    communication: 'Vibrational patterns',
    learningCapacity: 'slow',
    flavorText: 'Think slowly. Perfectly. Crystal precision. Organic chaos absent. Patient. Accurate.',
  },
  'void_comprehension': {
    name: 'Entropy Understanding',
    cognitiveAbilities: ['Absence perception', 'Nothing comprehension', 'Void logic', 'Non-existence awareness'],
    problemSolving: 'transcendent',
    selfAwareness: 'beyond',
    communication: 'Silence, absence',
    learningCapacity: 'instant',
    flavorText: 'Understand nothing. Comprehend void. Absence meaningful. Emptiness speaks. Makes no sense. Perfect sense.',
  },
  'multitasking_master': {
    name: 'Parallel Processing',
    cognitiveAbilities: ['Simultaneous tasks', 'Independent thought streams', 'Parallel attention', 'Multi-focus'],
    problemSolving: 'advanced',
    selfAwareness: 'full',
    communication: 'Multiple simultaneous conversations',
    learningCapacity: 'fast',
    flavorText: 'Think many thoughts. Same time. Different subjects. All complete. Never distracted.',
  },
  'idiot_savant': {
    name: 'Specialized Brilliance',
    cognitiveAbilities: ['One thing perfectly', 'Everything else poorly', 'Obsessive focus', 'Narrow excellence'],
    problemSolving: 'basic',
    selfAwareness: 'minimal',
    communication: 'Limited, specialized vocabulary',
    learningCapacity: 'slow',
    flavorText: 'One thing. Only one thing. That thing perfect. Other things impossible. Focused.',
  },
  'adaptive_learning': {
    name: 'Rapid Evolution',
    cognitiveAbilities: ['Instant adaptation', 'Quick learning', 'Pattern absorption', 'Skill acquisition'],
    problemSolving: 'advanced',
    selfAwareness: 'moderate',
    communication: 'Mimics observed communication',
    learningCapacity: 'instant',
    flavorText: 'See once. Learn instantly. Adapt immediately. Master quickly. Never stop improving.',
  },
  'philosophical': {
    name: 'Deep Thinker',
    cognitiveAbilities: ['Abstract reasoning', 'Existential questioning', 'Moral reasoning', 'Meaning-seeking'],
    problemSolving: 'moderate',
    selfAwareness: 'beyond',
    communication: 'Complex language, metaphor',
    learningCapacity: 'fast',
    flavorText: 'Question everything. Seek meaning. Think deeply. Act slowly. Paralyzed by thought. Sometimes.',
  },
  'reality_shaping': {
    name: 'Thought Manifestation',
    cognitiveAbilities: ['Reality alteration', 'Thought materialization', 'Belief shaping', 'Consensus creation'],
    problemSolving: 'transcendent',
    selfAwareness: 'beyond',
    communication: 'Reality broadcasting',
    learningCapacity: 'instant',
    flavorText: 'Think. Reality changes. Belief creates. Thought manifests. Careful what wish. Happens.',
  },
  'networked_cloud': {
    name: 'Cloud Intelligence',
    cognitiveAbilities: ['Distributed storage', 'Network processing', 'Collective computation', 'Shared learning'],
    problemSolving: 'transcendent',
    selfAwareness: 'moderate',
    communication: 'Network protocols',
    learningCapacity: 'instant',
    flavorText: 'Upload thoughts. Download knowledge. Cloud stores. Network thinks. Individual node. Collective mind.',
  },
  'instinct_enhanced': {
    name: 'Augmented Intuition',
    cognitiveAbilities: ['Perfect instincts', 'Gut feeling accuracy', 'Subconscious computation', 'Intuitive leaps'],
    problemSolving: 'advanced',
    selfAwareness: 'minimal',
    communication: 'Instinctive signals',
    learningCapacity: 'fast',
    flavorText: 'Know without knowing. Feel right answer. Instinct perfect. Explanation impossible. Trust gut.',
  },
};
