/**
 * Creature Reproduction Strategies
 *
 * How alien creatures create offspring and continue their species.
 * Because biology finds infinite ways to make more biology.
 */

export interface ReproductionStrategy {
  name: string;
  mechanism: string;
  offspringCount: string;
  parentalInvolvement: 'none' | 'minimal' | 'moderate' | 'extensive' | 'lifelong';
  geneticVariation: 'none' | 'low' | 'moderate' | 'high' | 'extreme';
  requirements: string[];
  flavorText: string;
}

export const REPRODUCTION_STRATEGIES: Record<string, ReproductionStrategy> = {
  'sexual_standard': {
    name: 'Two-Parent Mating',
    mechanism: 'Genetic material from two parents combines',
    offspringCount: '1-10 per cycle',
    parentalInvolvement: 'extensive',
    geneticVariation: 'high',
    requirements: ['Two compatible parents', 'Mating behavior', 'Gestation period'],
    flavorText: 'Two parents. Genes mix. Offspring unique. Variation high. Evolution approves.',
  },
  'asexual_budding': {
    name: 'Vegetative Budding',
    mechanism: 'Grows offspring directly from body',
    offspringCount: '1-5 per cycle',
    parentalInvolvement: 'minimal',
    geneticVariation: 'none',
    requirements: ['Mature parent', 'Energy reserves', 'Space'],
    flavorText: 'Bud grows. Separates. Clone created. Identical. Efficient. Boring genetics.',
  },
  'egg_laying': {
    name: 'External Egg Development',
    mechanism: 'Lays eggs that develop externally',
    offspringCount: '5-100 eggs',
    parentalInvolvement: 'moderate',
    geneticVariation: 'high',
    requirements: ['Egg production', 'Safe nesting site', 'Incubation conditions'],
    flavorText: 'Lay eggs. Many eggs. Guard them. Some survive. Numbers over care.',
  },
  'live_birth': {
    name: 'Internal Gestation',
    mechanism: 'Offspring develops inside parent',
    offspringCount: '1-4 per cycle',
    parentalInvolvement: 'extensive',
    geneticVariation: 'high',
    requirements: ['Gestation period', 'Nutrient transfer', 'Birth process'],
    flavorText: 'Grow inside. Fed by parent. Born alive. Invested. Survival higher.',
  },
  'spore_dispersal': {
    name: 'Microscopic Propagation',
    mechanism: 'Releases millions of spores',
    offspringCount: 'Millions',
    parentalInvolvement: 'none',
    geneticVariation: 'low',
    requirements: ['Spore production', 'Dispersal mechanism', 'Suitable substrate'],
    flavorText: 'Release spores. Millions. Billions. Few survive. Enough. Quantity strategy.',
  },
  'fission': {
    name: 'Binary Division',
    mechanism: 'Splits into two identical organisms',
    offspringCount: '2 per division',
    parentalInvolvement: 'none',
    geneticVariation: 'none',
    requirements: ['Critical mass', 'Division trigger'],
    flavorText: 'Grow large. Split. Two now. Both parent. Both child. Identity unclear.',
  },
  'metamorphosis': {
    name: 'Radical Life Stage',
    mechanism: 'Offspring transforms through distinct forms',
    offspringCount: '10-100 initial',
    parentalInvolvement: 'minimal',
    geneticVariation: 'moderate',
    requirements: ['Multiple life stages', 'Transformation triggers', 'Different environments'],
    flavorText: 'Hatch one form. Transform. Become another. Repeat. Final form reproduces.',
  },
  'fragmentation': {
    name: 'Breaking Apart',
    mechanism: 'Body fragments each become new organism',
    offspringCount: 'Variable by damage',
    parentalInvolvement: 'none',
    geneticVariation: 'none',
    requirements: ['Regenerative ability', 'Fragmentation event'],
    flavorText: 'Break apart. Each piece grows. Many offspring. Accidental reproduction. Damage creates life.',
  },
  'parasitic_implantation': {
    name: 'Host Incubation',
    mechanism: 'Implants offspring in living hosts',
    offspringCount: '1-10 per host',
    parentalInvolvement: 'minimal',
    geneticVariation: 'moderate',
    requirements: ['Suitable host', 'Implantation mechanism', 'Host survival (optional)'],
    flavorText: 'Implant in host. Grow inside. Burst out. Host dies. Usually. Effective.',
  },
  'conjugation': {
    name: 'Genetic Exchange',
    mechanism: 'Temporary connection transfers genetic material',
    offspringCount: 'Enhanced parent',
    parentalInvolvement: 'minimal',
    geneticVariation: 'high',
    requirements: ['Compatible partner', 'Physical connection', 'Gene transfer'],
    flavorText: 'Connect temporarily. Exchange genes. Separate. Both changed. Both reproduce.',
  },
  'time_loop_birth': {
    name: 'Causal Reproduction',
    mechanism: 'Offspring becomes own parent via time travel',
    offspringCount: 'Paradoxical',
    parentalInvolvement: 'lifelong',
    geneticVariation: 'none',
    requirements: ['Time travel', 'Stable loop', 'Causality tolerance'],
    flavorText: 'Birth self. Become parent. Loop eternal. No evolution. Perfect stability. Headache.',
  },
  'quantum_splitting': {
    name: 'Probability Division',
    mechanism: 'Quantum superposition creates multiple offspring',
    offspringCount: 'Multiple probable outcomes',
    parentalInvolvement: 'moderate',
    geneticVariation: 'extreme',
    requirements: ['Quantum instability', 'Observation', 'Multiple outcomes'],
    flavorText: 'Split into possibilities. Each real. Multiple offspring. Genetics varied. Quantum.',
  },
  'memory_transfer': {
    name: 'Consciousness Copying',
    mechanism: 'Transfers consciousness to new body',
    offspringCount: '1 at a time',
    parentalInvolvement: 'extensive',
    geneticVariation: 'low',
    requirements: ['New vessel', 'Memory encoding', 'Transfer mechanism'],
    flavorText: 'Copy mind. New body. Same person. New flesh. Immortality achieved. Sort of.',
  },
  'symbiotic_merger': {
    name: 'Species Fusion',
    mechanism: 'Two species combine to create offspring',
    offspringCount: '1-3 hybrids',
    parentalInvolvement: 'extensive',
    geneticVariation: 'extreme',
    requirements: ['Compatible species', 'Genetic compatibility', 'Merger process'],
    flavorText: 'Two species. Combine. Hybrid offspring. New species. Evolution accelerated.',
  },
  'dream_manifestation': {
    name: 'Oneiric Creation',
    mechanism: 'Dreams become real offspring',
    offspringCount: 'Variable by dream',
    parentalInvolvement: 'minimal',
    geneticVariation: 'extreme',
    requirements: ['Vivid dreams', 'Reality manifestation', 'Subconscious creation'],
    flavorText: 'Dream children. Wake to offspring. Unexpected. Random. Subconscious parents.',
  },
  'crystalline_growth': {
    name: 'Mineral Propagation',
    mechanism: 'Grows new crystals with consciousness',
    offspringCount: 'Dozens',
    parentalInvolvement: 'minimal',
    geneticVariation: 'low',
    requirements: ['Crystal lattice', 'Mineral nutrients', 'Growth medium'],
    flavorText: 'Grow crystals. Consciousness transfers. Mineral offspring. Slow. Beautiful. Alive.',
  },
  'viral_replication': {
    name: 'Infectious Reproduction',
    mechanism: 'Converts others into own species',
    offspringCount: 'Exponential',
    parentalInvolvement: 'none',
    geneticVariation: 'moderate',
    requirements: ['Infection vector', 'Vulnerable hosts', 'Conversion mechanism'],
    flavorText: 'Infect others. Convert biology. New members. Exponential growth. Concerning.',
  },
  'parthenogenesis': {
    name: 'Virgin Birth',
    mechanism: 'Offspring from unfertilized eggs',
    offspringCount: '1-10',
    parentalInvolvement: 'moderate',
    geneticVariation: 'low',
    requirements: ['No mate needed', 'Egg development'],
    flavorText: 'No partner. Offspring anyway. Clone or variant. Self-sufficient. Convenient.',
  },
  'hive_spawning': {
    name: 'Collective Birth',
    mechanism: 'Entire hive produces single offspring',
    offspringCount: '1 significant offspring',
    parentalInvolvement: 'extensive',
    geneticVariation: 'moderate',
    requirements: ['Entire colony', 'Collective resources', 'Hive coordination'],
    flavorText: 'Whole hive contributes. One offspring. All parents. Significant. Invested.',
  },
  'emotional_conception': {
    name: 'Feeling-Born',
    mechanism: 'Strong emotions create offspring',
    offspringCount: 'Variable by emotion',
    parentalInvolvement: 'minimal',
    geneticVariation: 'extreme',
    requirements: ['Intense emotion', 'Manifestation power', 'Emotional energy'],
    flavorText: 'Feel strongly. Offspring appears. Joy creates. Anger creates. All emotions fertile.',
  },
  'dimensional_seeding': {
    name: 'Cross-Reality Reproduction',
    mechanism: 'Seeds offspring into parallel dimensions',
    offspringCount: 'Unknown - dimensional',
    parentalInvolvement: 'none',
    geneticVariation: 'extreme',
    requirements: ['Dimensional access', 'Reality seeds', 'Multiverse'],
    flavorText: 'Send seeds elsewhere. Other dimensions. Other realities. Offspring everywhere. Nowhere.',
  },
  'radiation_mutation': {
    name: 'Induced Variation',
    mechanism: 'Radiation creates mutant offspring',
    offspringCount: '1-5 mutants',
    parentalInvolvement: 'minimal',
    geneticVariation: 'extreme',
    requirements: ['Radiation source', 'Mutation tolerance', 'Genetic instability'],
    flavorText: 'Expose to radiation. Offspring mutate. Variation extreme. Evolution rapid. Cancer common.',
  },
  'telepathic_breeding': {
    name: 'Mental Conception',
    mechanism: 'Minds merge to create new consciousness',
    offspringCount: '1 mental offspring',
    parentalInvolvement: 'extensive',
    geneticVariation: 'moderate',
    requirements: ['Two minds', 'Mental merger', 'Consciousness creation'],
    flavorText: 'Minds merge. New mind emerges. Mental offspring. Needs body. Eventually.',
  },
  'energy_condensation': {
    name: 'Matter Formation',
    mechanism: 'Condenses energy into living matter',
    offspringCount: '1-3',
    parentalInvolvement: 'moderate',
    geneticVariation: 'low',
    requirements: ['Energy reserves', 'Condensation process', 'Matter formation'],
    flavorText: 'Gather energy. Condense. Matter forms. Life emerges. Energy to flesh.',
  },
  'death_spawning': {
    name: 'Posthumous Birth',
    mechanism: 'Offspring emerge only when parent dies',
    offspringCount: '10-100',
    parentalInvolvement: 'none',
    geneticVariation: 'moderate',
    requirements: ['Parent death', 'Stored offspring', 'Death trigger'],
    flavorText: 'Parent dies. Offspring released. Death creates life. Sacrifice reproduction. Legacy.',
  },
};
