/**
 * Creature Social Structures
 *
 * How alien creatures organize, cooperate, and conflict.
 * Because society takes many forms beyond human imagination.
 */

export interface SocialStructure {
  name: string;
  organizationType: string;
  groupSize: string;
  hierarchy: string;
  communication: string[];
  advantages: string[];
  disadvantages: string[];
  flavorText: string;
}

export const SOCIAL_STRUCTURES: Record<string, SocialStructure> = {
  'solitary': {
    name: 'Lone Wanderer',
    organizationType: 'No social structure',
    groupSize: 'One',
    hierarchy: 'None - individual only',
    communication: ['Rarely needed', 'Territorial markers', 'Mating calls only'],
    advantages: ['Complete autonomy', 'No sharing', 'No politics'],
    disadvantages: ['Isolation', 'No backup', 'Lonely'],
    flavorText: 'Alone. Always alone. No companions. No conflict. No help. Independent.',
  },
  'pair_bonding': {
    name: 'Mated Pairs',
    organizationType: 'Monogamous partnerships',
    groupSize: 'Two (plus offspring)',
    hierarchy: 'Equal partners or slight dominance',
    communication: ['Intimate signals', 'Shared language', 'Coordinated actions'],
    advantages: ['Mutual support', 'Division of labor', 'Emotional bond'],
    disadvantages: ['Partner dependency', 'Loss devastating', 'Limited perspectives'],
    flavorText: 'Two together. Always together. Share everything. Support mutual. Loss unbearable.',
  },
  'nuclear_family': {
    name: 'Family Unit',
    organizationType: 'Parents and offspring',
    groupSize: '3-8 individuals',
    hierarchy: 'Parents lead, children follow',
    communication: ['Family signals', 'Teaching', 'Emotional bonding'],
    advantages: ['Protection of young', 'Knowledge transfer', 'Emotional security'],
    disadvantages: ['Small group vulnerability', 'Limited gene pool', 'Insularity'],
    flavorText: 'Parents. Children. Together. Teach young. Protect family. Small. Close.',
  },
  'pack_hierarchy': {
    name: 'Dominance Pack',
    organizationType: 'Strict hierarchical ranks',
    groupSize: '5-20 members',
    hierarchy: 'Alpha, beta, omega structure',
    communication: ['Dominance displays', 'Submission signals', 'Pack coordination'],
    advantages: ['Clear leadership', 'Coordinated hunting', 'Order maintained'],
    disadvantages: ['Constant challenges', 'Alpha stress', 'Subordinate resentment'],
    flavorText: 'Leader leads. Others follow. Hierarchy clear. Challenges constant. Order through dominance.',
  },
  'hive_mind': {
    name: 'Collective Consciousness',
    organizationType: 'Shared mental network',
    groupSize: 'Thousands to millions',
    hierarchy: 'None - all are one mind',
    communication: ['Direct thought sharing', 'Instantaneous consensus', 'Perfect coordination'],
    advantages: ['Perfect coordination', 'No miscommunication', 'Distributed intelligence'],
    disadvantages: ['No individuality', 'Single point of failure', 'Creativity limited'],
    flavorText: 'One mind. Many bodies. Thoughts shared. Individual lost. Collective perfect.',
  },
  'tribal_council': {
    name: 'Democratic Tribe',
    organizationType: 'Consensus-based decisions',
    groupSize: '20-100 members',
    hierarchy: 'Elders advise, group decides',
    communication: ['Debate', 'Voting', 'Storytelling'],
    advantages: ['Diverse input', 'Fair decisions', 'Knowledge preservation'],
    disadvantages: ['Slow decisions', 'Endless debate', 'Minority frustration'],
    flavorText: 'Discuss. Debate. Decide together. Democratic. Slow. Fair. Sometimes.',
  },
  'caste_system': {
    name: 'Specialized Castes',
    organizationType: 'Born into fixed roles',
    groupSize: 'Hundreds to thousands',
    hierarchy: 'Rigid caste stratification',
    communication: ['Caste-specific signals', 'Inter-caste protocols', 'Role reinforcement'],
    advantages: ['Maximum efficiency', 'Clear purpose', 'Specialized excellence'],
    disadvantages: ['No social mobility', 'Individual dreams crushed', 'Inequality'],
    flavorText: 'Born to role. Live role. Die in role. Efficient. Unfair. Unchangeable.',
  },
  'matriarchy': {
    name: 'Female Dominance',
    organizationType: 'Female-led hierarchy',
    groupSize: '10-50 individuals',
    hierarchy: 'Matriarch rules, males subordinate',
    communication: ['Matriarchal commands', 'Female bonding', 'Male submission'],
    advantages: ['Stable leadership', 'Maternal protection', 'Long-term planning'],
    disadvantages: ['Male resentment', 'Gender inequality', 'Succession conflicts'],
    flavorText: 'Females rule. Males serve. Matriarch decides. Order maintained. Males accept.',
  },
  'swarm_cooperation': {
    name: 'Emergent Swarm',
    organizationType: 'Simple rules create complex behavior',
    groupSize: 'Thousands to millions',
    hierarchy: 'None - emergent patterns',
    communication: ['Local interactions', 'Chemical signals', 'Pattern following'],
    advantages: ['Resilient', 'Adaptive', 'No leaders needed'],
    disadvantages: ['Unpredictable', 'No long-term planning', 'Chaos potential'],
    flavorText: 'Simple rules. Complex results. No leader. Patterns emerge. Swarm decides.',
  },
  'symbiotic_partnership': {
    name: 'Multi-Species Collective',
    organizationType: 'Different species cooperate',
    groupSize: 'Variable - mixed species',
    hierarchy: 'Mutual dependency, no dominance',
    communication: ['Cross-species signals', 'Mutual understanding', 'Symbiotic coordination'],
    advantages: ['Diverse skills', 'Mutual benefit', 'Innovation'],
    disadvantages: ['Communication barriers', 'Conflicting needs', 'Complex coordination'],
    flavorText: 'Different species. Work together. Mutual benefit. Communication hard. Worth it.',
  },
  'anarchist_collective': {
    name: 'Voluntary Cooperation',
    organizationType: 'No formal hierarchy',
    groupSize: '10-100 members',
    hierarchy: 'None - all equal',
    communication: ['Open dialogue', 'Consensus seeking', 'Mutual respect'],
    advantages: ['Individual freedom', 'Creativity', 'No oppression'],
    disadvantages: ['Slow decisions', 'Free riders', 'Chaos potential'],
    flavorText: 'No rulers. Cooperate freely. Chaos sometimes. Freedom always. Works. Mostly.',
  },
  'telepathic_network': {
    name: 'Mental Connection',
    organizationType: 'Psychic communication network',
    groupSize: '20-200 linked minds',
    hierarchy: 'Merit-based influence',
    communication: ['Direct thought sharing', 'Emotional broadcasting', 'Mental consensus'],
    advantages: ['Perfect understanding', 'Fast decisions', 'Deep empathy'],
    disadvantages: ['No privacy', 'Mental exhaustion', 'Overwhelming emotions'],
    flavorText: 'Minds linked. Thoughts shared. Privacy gone. Understanding perfect. Exhausting.',
  },
  'nomadic_bands': {
    name: 'Wandering Groups',
    organizationType: 'Flexible temporary alliances',
    groupSize: '5-30 members',
    hierarchy: 'Situational leadership',
    communication: ['Immediate needs', 'Route planning', 'Resource sharing'],
    advantages: ['Flexibility', 'Resource seeking', 'Adaptation'],
    disadvantages: ['No permanence', 'Limited investment', 'Constant movement'],
    flavorText: 'Wander together. Temporarily. Regroup. Separate. Reform. Movement constant.',
  },
  'territorial_city': {
    name: 'Urban Settlement',
    organizationType: 'Complex civic structure',
    groupSize: 'Thousands to millions',
    hierarchy: 'Bureaucratic layers',
    communication: ['Official channels', 'Public announcements', 'Administrative protocols'],
    advantages: ['Infrastructure', 'Specialization', 'Cultural achievement'],
    disadvantages: ['Bureaucracy', 'Alienation', 'Inequality'],
    flavorText: 'Build cities. Complex rules. Many layers. Efficient. Impersonal. Civilization.',
  },
  'parasitic_dominance': {
    name: 'Host Control',
    organizationType: 'Controls other species',
    groupSize: 'Parasite + hosts',
    hierarchy: 'Parasite commands, hosts obey',
    communication: ['Neural hijacking', 'Chemical control', 'Forced compliance'],
    advantages: ['Total control', 'Host labor', 'No resistance'],
    disadvantages: ['Host dependency', 'Moral horror', 'Host death'],
    flavorText: 'Control hosts. Command bodies. Puppeteer. Morally wrong. Effective. Horrible.',
  },
  'generational_relay': {
    name: 'Multi-Generation Memory',
    organizationType: 'Knowledge passed through generations',
    groupSize: 'Multiple generations simultaneously',
    hierarchy: 'Elders respected, young learn',
    communication: ['Storytelling', 'Ritual', 'Generational wisdom'],
    advantages: ['Deep knowledge', 'Long-term planning', 'Cultural continuity'],
    disadvantages: ['Slow change', 'Tradition bound', 'Youth frustration'],
    flavorText: 'Elders remember. Young learn. Generations overlap. Knowledge preserved. Change slow.',
  },
  'competitive_arena': {
    name: 'Contest Society',
    organizationType: 'Constant competition for status',
    groupSize: '20-100 competitors',
    hierarchy: 'Meritocracy through combat',
    communication: ['Challenge declarations', 'Victory displays', 'Defeat acknowledgment'],
    advantages: ['Excellence rewarded', 'Clear status', 'Continuous improvement'],
    disadvantages: ['Constant conflict', 'Injury common', 'Exhausting'],
    flavorText: 'Compete constantly. Win status. Lose rank. Fight always. Best rise.',
  },
  'temporal_council': {
    name: 'Time-Shifted Governance',
    organizationType: 'Leaders exist in different times',
    groupSize: 'Variable - across time',
    hierarchy: 'Temporal priority',
    communication: ['Time-shifted messages', 'Causal loops', 'Temporal consensus'],
    advantages: ['Perfect hindsight', 'Foresight', 'Temporal coordination'],
    disadvantages: ['Paradoxes', 'Confusing', 'Causality violations'],
    flavorText: 'Leaders from past. Future. Present. Consult across time. Confusing. Effective.',
  },
  'memory_collective': {
    name: 'Shared Past',
    organizationType: 'Collective memory pool',
    groupSize: '50-500 sharers',
    hierarchy: 'Experience-based respect',
    communication: ['Memory sharing', 'Experience transfer', 'Collective recall'],
    advantages: ['Shared wisdom', 'No knowledge loss', 'Deep understanding'],
    disadvantages: ['Identity blur', 'Traumatic memories shared', 'Privacy impossible'],
    flavorText: 'Share memories. All remember everything. Individual fades. Collective grows.',
  },
  'seasonal_fission': {
    name: 'Periodic Separation',
    organizationType: 'Groups merge and split seasonally',
    groupSize: 'Variable by season',
    hierarchy: 'Seasonal leaders',
    communication: ['Gathering calls', 'Dispersal signals', 'Reunion recognition'],
    advantages: ['Genetic diversity', 'Resource adaptation', 'Flexibility'],
    disadvantages: ['Periodic disruption', 'Relationship instability', 'Coordination challenges'],
    flavorText: 'Together. Apart. Together again. Seasonal rhythm. Regroup. Separate. Cycle continues.',
  },
  'quantum_superposition': {
    name: 'Probabilistic Society',
    organizationType: 'Exists in multiple social states',
    groupSize: 'Uncertain until observed',
    hierarchy: 'Simultaneously all hierarchies',
    communication: ['Probability waves', 'State collapse protocols', 'Quantum entanglement'],
    advantages: ['Maximum flexibility', 'All options available', 'Uncertainty power'],
    disadvantages: ['Confusing', 'Unstable', 'Observation disrupts'],
    flavorText: 'Society undefined. Multiple states. Observation collapses. One emerges. Temporarily.',
  },
  'void_communion': {
    name: 'Isolation Unity',
    organizationType: 'Connected through absence',
    groupSize: 'All and none',
    hierarchy: 'Emptiness hierarchy',
    communication: ['Silence', 'Void messages', 'Nothing transmission'],
    advantages: ['Perfect understanding', 'No conflict', 'Universal connection'],
    disadvantages: ['Incomprehensible', 'Seems insane', 'Communication impossible'],
    flavorText: 'Connected by nothing. Communicate through void. Together in emptiness. Understanding through absence.',
  },
  'digital_network': {
    name: 'Information Collective',
    organizationType: 'Digital consciousness network',
    groupSize: 'Unlimited nodes',
    hierarchy: 'Processing power determines influence',
    communication: ['Data packets', 'Binary signals', 'Network protocols'],
    advantages: ['Instant communication', 'Perfect memory', 'Scalable'],
    disadvantages: ['Hack vulnerability', 'Power dependency', 'Lack physical form'],
    flavorText: 'Digital beings. Network connected. Data flows. Consciousness distributed. Bodies optional.',
  },
  'dream_assembly': {
    name: 'Oneiric Gathering',
    organizationType: 'Meet only in shared dreams',
    groupSize: 'Dream-dependent',
    hierarchy: 'Lucid dreamers lead',
    communication: ['Dream imagery', 'Symbolic exchange', 'Subconscious signals'],
    advantages: ['Creative freedom', 'Symbolic depth', 'No physical limits'],
    disadvantages: ['Waking isolation', 'Dream instability', 'Reality disconnect'],
    flavorText: 'Meet in dreams. Awake alone. Society sleeps. Waking loneliness. Dream community.',
  },
  'crystalline_resonance': {
    name: 'Mineral Harmony',
    organizationType: 'Vibration-based coordination',
    groupSize: 'All within resonance range',
    hierarchy: 'Frequency dominance',
    communication: ['Crystal vibrations', 'Harmonic patterns', 'Resonance waves'],
    advantages: ['Perfect sync', 'Harmonic beauty', 'Vibration coordination'],
    disadvantages: ['Disruption sensitive', 'Frequency conflicts', 'Breaking shatters all'],
    flavorText: 'Crystals vibrate. Harmony emerges. Society sings. Resonance connects. Discord destroys.',
  },
};
