/**
 * ProfessionComponent - Defines agent profession and work simulation
 *
 * This component enables background profession simulation for NPC city workers.
 * Works with CityDirectorSystem to coordinate city-wide profession distribution.
 *
 * Key features:
 * - Links agents to workplaces (TV stations, newspapers, radio stations)
 * - Tracks daily output quotas (articles, shows, broadcasts)
 * - Enables scripted profession behaviors for autonomic agents
 * - No individual LLM calls - uses templates + city director coordination
 */

import type { Component } from '../ecs/Component.js';

/**
 * Profession roles for NPC city workers.
 */
export type ProfessionRole =
  // Media professions
  | 'newspaper_reporter'
  | 'newspaper_editor'
  | 'tv_actor'
  | 'tv_director'
  | 'tv_producer'
  | 'tv_writer'
  | 'radio_dj'
  | 'radio_producer'
  // Service professions
  | 'office_worker'
  | 'shopkeeper'
  | 'teacher'
  | 'librarian'
  | 'doctor'
  | 'nurse'
  // Administrative professions
  | 'bureaucrat'
  | 'city_planner'
  | 'accountant'
  // Other
  | 'generic_worker';

/**
 * Work shift schedule for profession.
 */
export interface WorkShift {
  /** Start time in game hours (0-23) */
  startHour: number;
  /** End time in game hours (0-23) */
  endHour: number;
  /** Days of week (0 = Sunday, 6 = Saturday). Empty = every day. */
  workDays?: number[];
}

/**
 * Profession output tracking.
 */
export interface ProfessionOutput {
  /** Type of output produced */
  type: 'news_article' | 'tv_episode' | 'radio_show' | 'service' | 'administrative';
  /** Description/content of output */
  content: string;
  /** Quality rating (0.0-1.0) */
  quality: number;
  /** Game tick when produced */
  producedTick: number;
  /** Associated building/entity ID if applicable */
  associatedId?: string;
}

/**
 * ProfessionComponent - Attached to agents with professions.
 */
export interface ProfessionComponent extends Component {
  type: 'profession';

  /** Role/job type */
  role: ProfessionRole;

  /** Building ID where this agent works (TV station, newspaper office, etc.) */
  workplaceBuildingId: string;

  /** City director entity ID (for coordination) */
  cityDirectorId: string;

  /** Work shift schedule */
  shift: WorkShift;

  /** Expected outputs per game day */
  dailyOutputQuota: number;

  /** Outputs produced (limited history, e.g., last 10) */
  recentOutputs: ProfessionOutput[];

  /** Current work state */
  currentWork?: {
    /** What they're working on */
    description: string;
    /** Progress 0.0-1.0 */
    progress: number;
    /** Started at tick */
    startedTick: number;
    /** Expected completion tick */
    expectedCompletionTick: number;
  };

  /** Performance rating (0.0-1.0) - affects quality */
  performance: number;

  /** Experience in this profession (affects quality) */
  experienceDays: number;

  /** Salary (for economic simulation) */
  salary: number;

  /** Hired at tick */
  hiredTick: number;

  /** Personality content (LLM-generated or templated) */
  personality?: {
    /** Catchphrases for this profession */
    catchphrases: string[];
    /** Show/segment intros (for media professions) */
    intros: string[];
    /** Personality quirks/traits */
    quirks: string[];
    /** Generated by LLM or template */
    generatedBy: 'llm' | 'template';
    /** Generation timestamp */
    generatedAt: number;
  };
}

// ============================================================================
// FACTORY FUNCTIONS
// ============================================================================

/**
 * Default work shifts by profession role.
 */
const DEFAULT_SHIFTS: Record<ProfessionRole, WorkShift> = {
  // Media - varying shifts
  newspaper_reporter: { startHour: 8, endHour: 17 }, // 9-5
  newspaper_editor: { startHour: 9, endHour: 18 },
  tv_actor: { startHour: 7, endHour: 19 }, // Long days during production
  tv_director: { startHour: 6, endHour: 20 },
  tv_producer: { startHour: 9, endHour: 18 },
  tv_writer: { startHour: 10, endHour: 18 },
  radio_dj: { startHour: 6, endHour: 14 }, // Morning show
  radio_producer: { startHour: 8, endHour: 16 },

  // Service - standard shifts
  office_worker: { startHour: 9, endHour: 17 },
  shopkeeper: { startHour: 9, endHour: 18 },
  teacher: { startHour: 8, endHour: 15 },
  librarian: { startHour: 10, endHour: 18 },
  doctor: { startHour: 8, endHour: 18 },
  nurse: { startHour: 7, endHour: 19 },

  // Administrative
  bureaucrat: { startHour: 9, endHour: 17 },
  city_planner: { startHour: 9, endHour: 17 },
  accountant: { startHour: 9, endHour: 17 },

  // Generic
  generic_worker: { startHour: 9, endHour: 17 },
};

/**
 * Default daily output quotas by profession.
 */
const DEFAULT_QUOTAS: Record<ProfessionRole, number> = {
  // Media - content creation
  newspaper_reporter: 2, // 2 articles per day
  newspaper_editor: 5, // Edit 5 articles per day
  tv_actor: 4, // 4 scenes per day
  tv_director: 3, // Direct 3 scenes per day
  tv_producer: 1, // Manage 1 production per day
  tv_writer: 3, // 3 script pages per day
  radio_dj: 1, // 1 show per day
  radio_producer: 2, // Produce 2 segments per day

  // Service - varies
  office_worker: 8, // 8 tasks per day
  shopkeeper: 20, // 20 customers per day
  teacher: 6, // 6 lessons per day
  librarian: 15, // 15 books processed per day
  doctor: 10, // 10 patients per day
  nurse: 15, // 15 patients assisted per day

  // Administrative
  bureaucrat: 5, // 5 forms processed per day
  city_planner: 2, // 2 plans reviewed per day
  accountant: 10, // 10 accounts processed per day

  // Generic
  generic_worker: 5,
};

/**
 * Default salaries by profession (in currency units per game day).
 */
const DEFAULT_SALARIES: Record<ProfessionRole, number> = {
  // Media - higher salaries
  newspaper_reporter: 100,
  newspaper_editor: 150,
  tv_actor: 200,
  tv_director: 250,
  tv_producer: 200,
  tv_writer: 120,
  radio_dj: 150,
  radio_producer: 100,

  // Service - medium salaries
  office_worker: 80,
  shopkeeper: 90,
  teacher: 110,
  librarian: 85,
  doctor: 300,
  nurse: 150,

  // Administrative
  bureaucrat: 95,
  city_planner: 130,
  accountant: 110,

  // Generic
  generic_worker: 70,
};

/**
 * Create a profession component with sensible defaults.
 */
export function createProfessionComponent(
  role: ProfessionRole,
  workplaceBuildingId: string,
  cityDirectorId: string,
  hiredTick: number,
  options?: {
    shift?: WorkShift;
    dailyOutputQuota?: number;
    salary?: number;
    performance?: number;
  }
): ProfessionComponent {
  return {
    type: 'profession',
    version: 1,
    role,
    workplaceBuildingId,
    cityDirectorId,
    shift: options?.shift ?? DEFAULT_SHIFTS[role],
    dailyOutputQuota: options?.dailyOutputQuota ?? DEFAULT_QUOTAS[role],
    recentOutputs: [],
    performance: options?.performance ?? 0.7, // Start at 70% performance
    experienceDays: 0,
    salary: options?.salary ?? DEFAULT_SALARIES[role],
    hiredTick,
  };
}

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Check if agent should be at work based on current time and shift.
 */
export function isWorkTime(profession: ProfessionComponent, currentHour: number, dayOfWeek: number): boolean {
  const { shift } = profession;

  // Check day of week if specified
  if (shift.workDays && shift.workDays.length > 0) {
    if (!shift.workDays.includes(dayOfWeek)) {
      return false;
    }
  }

  // Check hour
  if (shift.startHour <= shift.endHour) {
    // Normal shift (e.g., 9-17)
    return currentHour >= shift.startHour && currentHour < shift.endHour;
  } else {
    // Overnight shift (e.g., 22-6)
    return currentHour >= shift.startHour || currentHour < shift.endHour;
  }
}

/**
 * Calculate expected quality of output based on performance and experience.
 */
export function calculateOutputQuality(profession: ProfessionComponent): number {
  // Base quality from performance rating
  const baseQuality = profession.performance;

  // Experience bonus (caps at 100 days for +0.2 quality)
  const experienceBonus = Math.min(profession.experienceDays / 100, 1.0) * 0.2;

  // Random variation (±0.1)
  const randomVariation = (Math.random() - 0.5) * 0.2;

  // Clamp to [0, 1]
  return Math.max(0, Math.min(1, baseQuality + experienceBonus + randomVariation));
}

/**
 * Add an output to profession history (maintains max 10 recent outputs).
 */
export function addProfessionOutput(
  profession: ProfessionComponent,
  output: ProfessionOutput
): void {
  profession.recentOutputs.push(output);

  // Keep only last 10 outputs
  if (profession.recentOutputs.length > 10) {
    profession.recentOutputs.shift();
  }

  // Clear current work
  profession.currentWork = undefined;
}

/**
 * Start new work item for profession.
 */
export function startProfessionWork(
  profession: ProfessionComponent,
  description: string,
  currentTick: number,
  durationTicks: number
): void {
  profession.currentWork = {
    description,
    progress: 0,
    startedTick: currentTick,
    expectedCompletionTick: currentTick + durationTicks,
  };
}

/**
 * Update work progress.
 */
export function updateWorkProgress(
  profession: ProfessionComponent,
  currentTick: number
): number {
  if (!profession.currentWork) {
    return 0;
  }

  const elapsed = currentTick - profession.currentWork.startedTick;
  const duration = profession.currentWork.expectedCompletionTick - profession.currentWork.startedTick;

  profession.currentWork.progress = Math.min(1.0, elapsed / duration);

  return profession.currentWork.progress;
}

/**
 * Check if current work is complete.
 */
export function isWorkComplete(profession: ProfessionComponent): boolean {
  return profession.currentWork !== undefined && profession.currentWork.progress >= 1.0;
}

/**
 * Get profession category (for grouping).
 */
export function getProfessionCategory(role: ProfessionRole): string {
  if (['newspaper_reporter', 'newspaper_editor', 'tv_actor', 'tv_director', 'tv_producer', 'tv_writer', 'radio_dj', 'radio_producer'].includes(role)) {
    return 'media';
  }
  if (['office_worker', 'shopkeeper', 'teacher', 'librarian', 'doctor', 'nurse'].includes(role)) {
    return 'service';
  }
  if (['bureaucrat', 'city_planner', 'accountant'].includes(role)) {
    return 'administrative';
  }
  return 'other';
}

/**
 * Get average output quality from recent outputs.
 */
export function getAverageOutputQuality(profession: ProfessionComponent): number {
  if (profession.recentOutputs.length === 0) {
    return profession.performance; // Default to performance rating
  }

  const sum = profession.recentOutputs.reduce((acc, output) => acc + output.quality, 0);
  return sum / profession.recentOutputs.length;
}
