/**
 * SoulIdentityComponent - The core essence and purpose of a soul
 *
 * Souls are separate entities from bodies/agents. They have:
 * - A purpose/destiny (LLM-generated at soul creation)
 * - Core interests that drive incarnations
 * - Cosmic alignment (fate/luck modifier)
 * - Potential for growth across incarnations
 *
 * This enables:
 * - Dream communication (soul talks to conscious mind)
 * - Astral projection (soul leaves body temporarily)
 * - Concurrent incarnations (same soul, multiple bodies)
 * - Lich mechanics (soul bound to phylactery)
 * - Soul-guided decision making
 */

import type { Component } from '../ecs/Component.js';

/**
 * Soul culture/origin types
 */
export type SoulCulture =
  | 'human'
  | 'elven'
  | 'dwarven'
  | 'orcish'
  | 'thrakeen'
  | 'exotic';

/**
 * Record of a single incarnation
 */
export interface IncarnationRecord {
  /** When this incarnation began */
  incarnationTick: number;

  /** When this incarnation ended (death tick) */
  deathTick?: number;

  /** Body name during this incarnation */
  bodyName?: string;

  /** Species of the body during this incarnation */
  bodySpecies?: string;

  /** How long this incarnation lasted (in ticks) */
  duration?: number;

  /** Major achievements or events during this life */
  notableEvents?: string[];

  /** Cause of death */
  causeOfDeath?: string;
}

export interface SoulIdentityComponent extends Component {
  type: 'soul_identity';

  /**
   * Unique soul name/identifier
   * Persistent across all incarnations
   * Reflects the culture/species of the soul's origin
   */
  soulName: string;

  /**
   * The culture/species of this soul's origin
   * Determines the soul's name and cultural identity
   * An elven soul might incarnate as a human, but remains an elven soul
   */
  soulOriginCulture: SoulCulture;

  /**
   * Whether this soul is reincarnated (vs newly created)
   */
  isReincarnated: boolean;

  /**
   * History of all incarnations this soul has experienced
   * Ordered chronologically (oldest first)
   */
  incarnationHistory: IncarnationRecord[];

  /**
   * Soul's fundamental purpose in the cosmos (LLM-generated)
   * Examples:
   * - "To unite fractured communities through shared stories"
   * - "To discover the true nature of the divine realms"
   * - "To protect the innocent from tyranny"
   * - "To master all forms of creation magic"
   */
  purpose: string;

  /**
   * Soul's potential destiny (LLM-generated, may or may not be fulfilled)
   * Examples:
   * - "Destined to become a bridge between mortals and gods"
   * - "Fated to uncover an ancient secret that reshapes the world"
   * - "Will either save or doom their bloodline"
   * - "Prophesied to transcend mortality through accumulated wisdom"
   */
  destiny?: string;

  /**
   * Core interests that the soul is born with
   * These influence what the incarnated body gravitates toward
   * Examples: ['magic', 'craftsmanship', 'nature', 'knowledge', 'combat', 'art']
   */
  coreInterests: string[];

  /**
   * Soul's cosmic alignment (-1 to 1)
   * - Negative: Cursed/unlucky souls, harder path
   * - Zero: Neutral fate
   * - Positive: Blessed/lucky souls, easier path
   */
  cosmicAlignment: number;

  /**
   * When this soul was first created (first incarnation tick)
   */
  soulBirthTick: number;

  /**
   * Soul archetype (influences purpose generation)
   * Examples: 'seeker', 'protector', 'creator', 'destroyer', 'unifier', 'wanderer'
   */
  archetype?: string;

  /**
   * Whether this soul has achieved its purpose
   */
  purposeFulfilled: boolean;

  /**
   * Whether this soul's destiny has been realized
   */
  destinyRealized: boolean;

  /**
   * Soul's moral/ethical alignment (can shift over incarnations)
   * Not good/evil binary, but tendencies
   */
  alignment?: {
    order: number;      // -1 (chaos) to 1 (order)
    altruism: number;   // -1 (selfish) to 1 (selfless)
    tradition: number;  // -1 (iconoclast) to 1 (traditionalist)
  };
}

/**
 * Create a new soul identity (called when soul is first created)
 * Purpose and destiny should be generated by LLM based on:
 * - Parent souls (if any)
 * - Cultural context
 * - Cosmic conditions at creation
 * - Random seed/fate
 */
export function createSoulIdentityComponent(data: {
  soulName: string;
  soulOriginCulture: SoulCulture;
  isReincarnated: boolean;
  purpose: string;
  destiny?: string;
  coreInterests: string[];
  cosmicAlignment?: number;
  currentTick: number;
  archetype?: string;
  incarnationHistory?: IncarnationRecord[];
}): SoulIdentityComponent {
  return {
    type: 'soul_identity',
    version: 1,
    soulName: data.soulName,
    soulOriginCulture: data.soulOriginCulture,
    isReincarnated: data.isReincarnated,
    incarnationHistory: data.incarnationHistory ?? [],
    purpose: data.purpose,
    destiny: data.destiny,
    coreInterests: data.coreInterests,
    cosmicAlignment: data.cosmicAlignment ?? 0,
    soulBirthTick: data.currentTick,
    archetype: data.archetype,
    purposeFulfilled: false,
    destinyRealized: false,
    alignment: {
      order: 0,
      altruism: 0,
      tradition: 0,
    },
  };
}

/**
 * Generate default interests based on archetype
 */
export function getDefaultInterestsForArchetype(archetype: string): string[] {
  const archetypeInterests: Record<string, string[]> = {
    seeker: ['exploration', 'knowledge', 'discovery', 'questioning'],
    protector: ['combat', 'defense', 'loyalty', 'guardianship'],
    creator: ['crafting', 'building', 'art', 'innovation'],
    destroyer: ['combat', 'chaos', 'revolution', 'transformation'],
    unifier: ['diplomacy', 'social', 'harmony', 'leadership'],
    wanderer: ['exploration', 'freedom', 'adaptation', 'stories'],
    mystic: ['magic', 'spirituality', 'mystery', 'divinity'],
    scholar: ['knowledge', 'teaching', 'research', 'wisdom'],
  };

  return archetypeInterests[archetype] ?? ['exploration', 'knowledge', 'social'];
}

/**
 * Check if soul has fulfilled its purpose based on experiences
 */
export function evaluatePurposeFulfillment(
  component: SoulIdentityComponent,
  _achievements: string[],
  _experienceSummary: string
): boolean {
  // This would ideally be evaluated by LLM comparing purpose to achievements
  // For now, just return current state
  return component.purposeFulfilled;
}

/**
 * Get a narrative description of the soul's journey
 */
export function getSoulNarrative(component: SoulIdentityComponent, livesLived: number): string {
  const { soulName, soulOriginCulture, purpose, archetype, purposeFulfilled, destinyRealized } = component;

  let narrative = `${soulName}, a ${soulOriginCulture} ${archetype ?? 'wandering'} soul`;

  if (livesLived === 1) {
    narrative += `, newly incarnated with the purpose: "${purpose}"`;
  } else {
    narrative += `, having lived ${livesLived} lives`;

    if (purposeFulfilled) {
      narrative += ', has fulfilled their purpose';
    } else {
      narrative += `, still seeking to: "${purpose}"`;
    }
  }

  if (destinyRealized && component.destiny) {
    narrative += `. Their destiny has been realized: "${component.destiny}"`;
  } else if (component.destiny) {
    narrative += `. Destiny awaits: "${component.destiny}"`;
  }

  return narrative;
}

/**
 * Add an incarnation record to the soul's history
 */
export function addIncarnationRecord(
  component: SoulIdentityComponent,
  record: IncarnationRecord
): void {
  component.incarnationHistory.push(record);
}

/**
 * Complete the current incarnation (called on death)
 */
export function completeCurrentIncarnation(
  component: SoulIdentityComponent,
  deathTick: number,
  causeOfDeath: string,
  notableEvents?: string[]
): void {
  const currentIncarnation = component.incarnationHistory[component.incarnationHistory.length - 1];
  if (currentIncarnation) {
    currentIncarnation.deathTick = deathTick;
    currentIncarnation.duration = deathTick - currentIncarnation.incarnationTick;
    currentIncarnation.causeOfDeath = causeOfDeath;
    if (notableEvents) {
      currentIncarnation.notableEvents = notableEvents;
    }
  }
}

/**
 * Get the total number of incarnations
 */
export function getIncarnationCount(component: SoulIdentityComponent): number {
  return component.incarnationHistory.length;
}

/**
 * Get the most recent incarnation
 */
export function getCurrentIncarnation(component: SoulIdentityComponent): IncarnationRecord | undefined {
  return component.incarnationHistory[component.incarnationHistory.length - 1];
}

/**
 * Get a summary of the soul's incarnation history
 */
export function getIncarnationHistorySummary(component: SoulIdentityComponent): string {
  const count = component.incarnationHistory.length;
  if (count === 0) {
    return 'No incarnations yet';
  }

  if (count === 1) {
    return 'First incarnation';
  }

  const incarnations = component.incarnationHistory;
  const species = new Set(incarnations.map(i => i.bodySpecies).filter(Boolean));
  const totalDuration = incarnations.reduce((sum, i) => sum + (i.duration ?? 0), 0);

  return `${count} incarnations across ${species.size} species (total: ${totalDuration} ticks)`;
}
