/**
 * Expanded Spell Library - Comprehensive spell definitions for all paradigms
 *
 * This file contains extensive spell lists written in the blended voice style:
 * - Baroque encyclopedic detail (comic-academic style)
 * - Dry cosmic pragmatism (bureaucratic-absurdist)
 * - Humane satire with moral clarity
 * - Lyrical intimate mythology (mythological-literary)
 */

import type { SpellDefinition } from './SpellRegistry.js';

// ============================================================================
// DIVINE PARADIGM SPELLS - Faith, Worship, and Miracles
// ============================================================================

export const DIVINE_SPELLS: SpellDefinition[] = [
  // === Restoration School ===
  {
    id: 'divine_heal',
    name: 'Divine Healing',
    paradigmId: 'divine',
    technique: 'enhance',
    form: 'body',
    source: 'divine',
    manaCost: 25,
    castTime: 40,
    range: 1,
    effectId: 'heal_effect',
    description: 'Channel divine power to mend wounds. The gods, it turns out, have surprisingly practical applications beyond smiting the unfaithful and demanding tribute. This is the entry-level miracle: predictable, safe, and only occasionally prone to curing ailments the patient didn\'t know they had.',
    school: 'restoration',
    baseMishapChance: 0.02,
    hotkeyable: true,
    icon: '✨',
    tags: ['divine', 'healing', 'support'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 3,
      leavesMagicalSignature: false,
      detectionNotes: 'Divine healing is god-granted and natural - rarely draws attention',
    },
  },
  {
    id: 'divine_mend_bone',
    name: 'Mend Bone',
    paradigmId: 'divine',
    technique: 'enhance',
    form: 'body',
    source: 'divine',
    manaCost: 35,
    castTime: 80,
    range: 1,
    effectId: 'heal_effect',
    description: 'Your god reaches into the target and sets their bones with the tender care of someone who designed the skeletal system in the first place and knows exactly where everything goes. Hurts considerably more than regular healing. This is theologically classified as "building character."',
    school: 'restoration',
    baseMishapChance: 0.04,
    hotkeyable: true,
    icon: '🦴',
    tags: ['divine', 'healing', 'bones'],
    prerequisites: ['divine_heal'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 3,
      leavesMagicalSignature: false,
      detectionNotes: 'God-granted healing of natural injuries',
    },
  },
  {
    id: 'divine_cure_poison',
    name: 'Purify Toxin',
    paradigmId: 'divine',
    technique: 'enhance',
    form: 'body',
    source: 'divine',
    manaCost: 30,
    castTime: 30,
    range: 1,
    effectId: 'heal_effect',
    description: 'Toxins are, fundamentally, just molecules in the wrong place. Your deity corrects this spatial misunderstanding. The poison doesn\'t vanish—that would violate conservation of mass—it simply finds itself suddenly outside the body, usually via the most expedient route. Standing downwind is inadvisable.',
    school: 'restoration',
    baseMishapChance: 0.03,
    hotkeyable: true,
    icon: '☠️',
    tags: ['divine', 'healing', 'poison'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 3,
      leavesMagicalSignature: false,
      detectionNotes: 'Natural divine cleansing',
    },
  },
  {
    id: 'divine_cure_disease',
    name: 'Cleansing Touch',
    paradigmId: 'divine',
    technique: 'enhance',
    form: 'body',
    source: 'divine',
    manaCost: 40,
    castTime: 60,
    range: 1,
    effectId: 'heal_effect',
    description: 'Disease is a theological problem: life consuming life in patterns the gods find aesthetically displeasing. You negotiate with your deity for corrective action. The prayer takes time because you\'re essentially filing form 77-D ("Request for Miraculous Intervention, Biological") in triplicate.',
    school: 'restoration',
    baseMishapChance: 0.05,
    hotkeyable: true,
    icon: '🩹',
    tags: ['divine', 'healing', 'disease'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 4,
      leavesMagicalSignature: false,
      detectionNotes: 'Divine disease cleansing - natural faith healing',
    },
  },
  {
    id: 'divine_regeneration',
    name: 'Blessed Regeneration',
    paradigmId: 'divine',
    technique: 'enhance',
    form: 'body',
    source: 'divine',
    manaCost: 35,
    castTime: 50,
    range: 1,
    duration: 1200,
    effectId: 'regeneration_effect',
    description: 'Grant ongoing divine healing over time. The target becomes a small, temporary branch office of divine healing energy. Wounds close. Cells replicate with unusual enthusiasm. The effect fades after a minute, at which point biology resumes its normal pace of begrudging repair.',
    school: 'restoration',
    baseMishapChance: 0.04,
    hotkeyable: true,
    icon: '💫',
    prerequisites: ['divine_heal'],
    tags: ['divine', 'healing', 'duration'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 4,
      leavesMagicalSignature: false,
      detectionNotes: 'Ongoing divine healing - natural faith magic',
    },
  },
  {
    id: 'divine_restore_limb',
    name: 'Restoration of the Flesh',
    paradigmId: 'divine',
    technique: 'enhance',
    form: 'body',
    source: 'divine',
    manaCost: 75,
    castTime: 180,
    range: 1,
    effectId: 'heal_effect',
    description: 'Regrowing lost limbs is technically possible, though it requires convincing your deity to essentially rewind local time for specific body parts while leaving the rest alone. The divine bureaucracy categorizes this as "Selective Temporal Reversal, Biological Only," which requires filling out seventeen forms and a personal letter explaining why you deserve fingers again.',
    school: 'restoration',
    baseMishapChance: 0.15,
    hotkeyable: true,
    icon: '🖐️',
    tags: ['divine', 'healing', 'advanced'],
    prerequisites: ['divine_mend_bone', 'divine_regeneration'],
    creatorDetection: {
      detectionRisk: 'moderate',
      powerLevel: 6,
      leavesMagicalSignature: true,
      detectionNotes: 'Significant divine miracle - limb regrowth approaches forbidden territory',
    },
  },
  {
    id: 'divine_resurrection_minor',
    name: 'Breath of Second Chances',
    paradigmId: 'divine',
    technique: 'enhance',
    form: 'spirit',
    source: 'divine',
    manaCost: 150,
    castTime: 300,
    range: 1,
    effectId: 'heal_effect',
    description: 'Death, from a divine perspective, is more of a suggestion than a rule. Recently deceased individuals—we\'re talking minutes here, not days—can be persuaded to return if you ask very nicely and your god happens to be in a lenient mood. The formerly dead often report the experience as "deeply uncomfortable" and "theologically confusing."',
    school: 'restoration',
    baseMishapChance: 0.25,
    hotkeyable: false,
    icon: '🕊️',
    tags: ['divine', 'healing', 'resurrection', 'legendary'],
    prerequisites: ['divine_restore_limb'],
    creatorDetection: {
      detectionRisk: 'critical',
      forbiddenCategories: ['resurrection'],
      powerLevel: 8,
      leavesMagicalSignature: true,
      detectionNotes: 'FORBIDDEN: Resurrection defies the natural order - immediate Supreme Creator intervention guaranteed',
    },
  },

  // === Protection & Warding School ===
  {
    id: 'divine_blessing',
    name: 'Divine Blessing',
    paradigmId: 'divine',
    technique: 'enhance',
    form: 'body',
    source: 'divine',
    manaCost: 40,
    castTime: 60,
    range: 5,
    duration: 6000,
    effectId: 'minor_ward_effect',
    description: 'Bestow divine protection upon a target. The gods, when asked politely, will occasionally extend a metaphorical hand to deflect harm. This manifests as a faint shimmer—barely visible—that suggests the universe is, for the next five minutes, mildly biased in the target\'s favor.',
    school: 'protection',
    baseMishapChance: 0.03,
    hotkeyable: true,
    icon: '🙏',
    tags: ['divine', 'protection', 'buff'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 4,
      leavesMagicalSignature: false,
      detectionNotes: 'Divine blessing - natural god-granted protection',
    },
  },
  {
    id: 'divine_sanctuary',
    name: 'Sanctuary',
    paradigmId: 'divine',
    technique: 'protect',
    form: 'body',
    source: 'divine',
    manaCost: 60,
    castTime: 80,
    range: 0,
    duration: 3600,
    effectId: 'major_shield_effect',
    description: 'Create a powerful divine shield around yourself. You become, temporarily, a walking temple—sacred ground that violence finds philosophically troubling. Attackers experience a profound sense that harming you would be in poor taste. Most take the hint.',
    school: 'protection',
    baseMishapChance: 0.05,
    hotkeyable: true,
    icon: '🛡️',
    prerequisites: ['divine_blessing'],
    tags: ['divine', 'protection', 'defense'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 5,
      leavesMagicalSignature: false,
      detectionNotes: 'Personal divine protection - sanctioned by the faithful\'s deity',
    },
  },
  {
    id: 'divine_circle_of_protection',
    name: 'Circle of Warding',
    paradigmId: 'divine',
    technique: 'protect',
    form: 'spirit',
    source: 'divine',
    manaCost: 70,
    castTime: 120,
    range: 10,
    duration: 1800,
    effectId: 'major_shield_effect',
    description: 'Inscribe a protective circle that repels malevolent entities. The boundary isn\'t physical—you can\'t touch it—but spirits, demons, and other incorporeal nuisances find they simply can\'t cross. They mill about outside looking frustrated, which is deeply satisfying.',
    school: 'protection',
    baseMishapChance: 0.08,
    hotkeyable: true,
    icon: '⭕',
    tags: ['divine', 'protection', 'area', 'spirit'],
    prerequisites: ['divine_sanctuary'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 5,
      leavesMagicalSignature: true,
      detectionNotes: 'Warding circle - legitimate divine protection against malevolent entities',
    },
  },
  {
    id: 'divine_shield_of_faith',
    name: 'Shield of Unwavering Faith',
    paradigmId: 'divine',
    technique: 'protect',
    form: 'spirit',
    source: 'divine',
    manaCost: 55,
    castTime: 45,
    range: 3,
    duration: 2400,
    effectId: 'major_shield_effect',
    description: 'Your certainty becomes armor. The strength of your belief—literal, measurable faith—condenses into a translucent barrier. The more devout you are, the stronger it holds. Doubt weakens it. This is one of the few spells where sincerity is mechanically relevant.',
    school: 'protection',
    baseMishapChance: 0.06,
    hotkeyable: true,
    icon: '🛡️',
    tags: ['divine', 'protection', 'faith'],
    prerequisites: ['divine_blessing'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 5,
      leavesMagicalSignature: false,
      detectionNotes: 'Faith-based protection - sincere belief channels divine favor naturally',
    },
  },

  // === Smiting & Combat School ===
  {
    id: 'divine_smite',
    name: 'Divine Smite',
    paradigmId: 'divine',
    technique: 'create',
    form: 'spirit',
    source: 'divine',
    manaCost: 50,
    castTime: 30,
    range: 15,
    effectId: 'lightning_strike_effect',
    description: 'Call down divine wrath upon an enemy. Your deity, having observed the target\'s behavior and found it wanting, delivers corrective action in the form of concentrated holy energy. It\'s less "smiting" in the Old Testament sense and more "extremely firm celestial feedback."',
    school: 'smiting',
    baseMishapChance: 0.1,
    hotkeyable: true,
    icon: '⚔️',
    tags: ['divine', 'damage', 'holy'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 5,
      leavesMagicalSignature: true,
      detectionNotes: 'Divine judgment - deity-sanctioned offensive magic',
    },
  },
  {
    id: 'divine_righteous_fire',
    name: 'Flame of Judgment',
    paradigmId: 'divine',
    technique: 'create',
    form: 'fire',
    source: 'divine',
    manaCost: 45,
    castTime: 40,
    range: 12,
    effectId: 'fireball_effect',
    description: 'Holy fire that burns the wicked. Theologically, this is fascinating: the flame discriminates based on moral standing. Innocents feel only warmth. The guilty burn. How it determines guilt remains a point of theological debate, though "asks the god directly" seems likely.',
    school: 'smiting',
    baseMishapChance: 0.12,
    hotkeyable: true,
    icon: '🔥',
    tags: ['divine', 'damage', 'fire', 'judgment'],
    prerequisites: ['divine_smite'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 5,
      leavesMagicalSignature: true,
      detectionNotes: 'Holy fire - divine judgment manifested through faithful servant',
    },
  },
  {
    id: 'divine_pillar_of_light',
    name: 'Pillar of Celestial Wrath',
    paradigmId: 'divine',
    technique: 'create',
    form: 'spirit',
    source: 'divine',
    manaCost: 80,
    castTime: 60,
    range: 20,
    effectId: 'lightning_strike_effect',
    description: 'A column of pure divine energy descends from the heavens. Subtle it is not. The entire neighborhood notices. Birds flee. The pious prostrate themselves. The guilty reconsider their life choices. The spell is less about damage—though there\'s plenty—and more about making a point.',
    school: 'smiting',
    baseMishapChance: 0.15,
    hotkeyable: true,
    icon: '🌟',
    tags: ['divine', 'damage', 'area', 'flashy'],
    prerequisites: ['divine_smite', 'divine_righteous_fire'],
    creatorDetection: {
      detectionRisk: 'moderate',
      powerLevel: 6,
      leavesMagicalSignature: true,
      detectionNotes: 'Major divine manifestation - flashy but sanctioned by deity',
    },
  },
  {
    id: 'divine_banishment',
    name: 'Divine Banishment',
    paradigmId: 'divine',
    technique: 'create',
    form: 'spirit',
    source: 'divine',
    manaCost: 90,
    castTime: 90,
    range: 10,
    effectId: 'lightning_strike_effect',
    description: 'Forcibly relocate an unwanted entity to another plane of existence. Your god essentially files an eviction notice with cosmic bureaucracy. Demons, spirits, and other planar tourists find themselves suddenly elsewhere—usually their home dimension, occasionally somewhere embarrassing.',
    school: 'smiting',
    baseMishapChance: 0.18,
    hotkeyable: true,
    icon: '🚪',
    tags: ['divine', 'banish', 'planar'],
    prerequisites: ['divine_pillar_of_light'],
    creatorDetection: {
      detectionRisk: 'moderate',
      forbiddenCategories: ['planar_travel'],
      powerLevel: 7,
      leavesMagicalSignature: true,
      detectionNotes: 'Planar manipulation - approaches forbidden territory but divine source provides some protection',
    },
  },
  {
    id: 'divine_turn_undead',
    name: 'Rebuke the Restless',
    paradigmId: 'divine',
    technique: 'create',
    form: 'spirit',
    source: 'divine',
    manaCost: 35,
    castTime: 20,
    range: 15,
    effectId: 'lightning_strike_effect',
    description: 'The undead, being fundamentally contrary to the natural order, find divine energy deeply unpleasant. You channel your god\'s disapproval directly at them. Lesser undead flee. Stronger ones flinch. The truly powerful ones look mildly annoyed, which is still something.',
    school: 'smiting',
    baseMishapChance: 0.06,
    hotkeyable: true,
    icon: '💀',
    tags: ['divine', 'undead', 'control'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 4,
      leavesMagicalSignature: true,
      detectionNotes: 'Repelling undead - divine magic correcting cosmic violations',
    },
  },

  // === Blessing & Enhancement School ===
  {
    id: 'divine_bless_weapon',
    name: 'Consecrated Edge',
    paradigmId: 'divine',
    technique: 'enhance',
    form: 'body',
    source: 'divine',
    manaCost: 30,
    castTime: 40,
    range: 1,
    duration: 1200,
    effectId: 'minor_ward_effect',
    description: 'Imbue a weapon with divine favor. The blade doesn\'t glow—that would be tacky—but it cuts with the certainty of righteousness. Particularly effective against creatures who are, technically speaking, abominations. Regular mortals notice only that you seem unusually confident.',
    school: 'blessing',
    baseMishapChance: 0.04,
    hotkeyable: true,
    icon: '⚔️',
    tags: ['divine', 'weapon', 'buff'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 3,
      leavesMagicalSignature: false,
      detectionNotes: 'Minor weapon blessing - temporary divine favor',
    },
  },
  {
    id: 'divine_bless_courage',
    name: 'Blessing of Valor',
    paradigmId: 'divine',
    technique: 'enhance',
    form: 'spirit',
    source: 'divine',
    manaCost: 25,
    castTime: 30,
    range: 5,
    duration: 900,
    effectId: 'minor_ward_effect',
    description: 'Fear, from a divine perspective, is a failure of perspective. You grant targets the ability to see their situation through divine eyes—specifically, eyes that know how the story ends. Courage becomes less an emotion and more a rational assessment that everything will, probably, work out.',
    school: 'blessing',
    baseMishapChance: 0.03,
    hotkeyable: true,
    icon: '💪',
    tags: ['divine', 'buff', 'mental'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 3,
      leavesMagicalSignature: false,
      detectionNotes: 'Mental blessing - faith-based courage enhancement',
    },
  },
  {
    id: 'divine_bless_endurance',
    name: 'Blessing of Fortitude',
    paradigmId: 'divine',
    technique: 'enhance',
    form: 'body',
    source: 'divine',
    manaCost: 35,
    castTime: 50,
    range: 5,
    duration: 1800,
    effectId: 'minor_ward_effect',
    description: 'The target becomes temporarily more durable—not stronger, but harder to break. Exhaustion happens more slowly. Pain feels distant. This isn\'t numbing; the body still reports damage, but the divine override says "noted, continuing anyway."',
    school: 'blessing',
    baseMishapChance: 0.05,
    hotkeyable: true,
    icon: '🏃',
    tags: ['divine', 'buff', 'endurance'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 4,
      leavesMagicalSignature: false,
      detectionNotes: 'Endurance blessing - divine body support',
    },
  },
  {
    id: 'divine_bless_wisdom',
    name: 'Blessing of Clarity',
    paradigmId: 'divine',
    technique: 'enhance',
    form: 'spirit',
    source: 'divine',
    manaCost: 40,
    castTime: 60,
    range: 1,
    duration: 600,
    effectId: 'heal_effect',
    description: 'Grant temporary divine insight. The target experiences ten minutes of unusual clarity—not intelligence exactly, but the ability to see patterns, connections, and which decisions are profoundly stupid. Afterward, they often report feeling "disappointed in past me."',
    school: 'blessing',
    baseMishapChance: 0.06,
    hotkeyable: true,
    icon: '🧠',
    tags: ['divine', 'buff', 'wisdom'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 4,
      leavesMagicalSignature: false,
      detectionNotes: 'Wisdom blessing - divine insight through prayer',
    },
  },

  // === Divination School ===
  {
    id: 'divine_detect_evil',
    name: 'Sense Malevolence',
    paradigmId: 'divine',
    technique: 'perceive',
    form: 'spirit',
    source: 'divine',
    manaCost: 20,
    castTime: 30,
    range: 20,
    duration: 600,
    effectId: 'detect_magic_effect',
    description: 'Evil, it turns out, has a distinct metaphysical scent. Not literal smell—more like a wrongness that catches in your divine perception. You detect creatures and objects that offend cosmic order. This is surprisingly useful, though "radiates evil" is sometimes just "having a bad day."',
    school: 'divination',
    baseMishapChance: 0.03,
    hotkeyable: true,
    icon: '👁️',
    tags: ['divine', 'detection', 'alignment'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 3,
      leavesMagicalSignature: false,
      detectionNotes: 'Divine perception - sensing cosmic alignment is natural for the faithful',
    },
  },
  {
    id: 'divine_augury',
    name: 'Glimpse of Providence',
    paradigmId: 'divine',
    technique: 'perceive',
    form: 'spirit',
    source: 'divine',
    manaCost: 50,
    castTime: 180,
    range: 0,
    effectId: 'detect_magic_effect',
    description: 'Ask your deity for guidance about a proposed course of action. The response comes as intuition: "favorable," "unfavorable," or "the gods are busy, try again later." Accuracy varies. Deities see futures as probability clouds, not certainties. Free will remains inconveniently relevant.',
    school: 'divination',
    baseMishapChance: 0.08,
    hotkeyable: false,
    icon: '🔮',
    tags: ['divine', 'divination', 'future'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 5,
      leavesMagicalSignature: false,
      detectionNotes: 'Asking deity for guidance - proper use of divine communication',
    },
  },
  {
    id: 'divine_tongues',
    name: 'Gift of Tongues',
    paradigmId: 'divine',
    technique: 'enhance',
    form: 'spirit',
    source: 'divine',
    manaCost: 35,
    castTime: 40,
    range: 5,
    duration: 1800,
    effectId: 'heal_effect',
    description: 'Grant understanding of all languages. The spell doesn\'t teach languages—that would take years—it simply routes all speech through divine translation services. Words you hear emerge in your native tongue. Words you speak arrive in the listener\'s. The gods\' customer service, it seems, includes interpretation.',
    school: 'divination',
    baseMishapChance: 0.04,
    hotkeyable: true,
    icon: '🗣️',
    tags: ['divine', 'language', 'communication'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 4,
      leavesMagicalSignature: false,
      detectionNotes: 'Divine translation service - gods facilitate communication between their creations',
    },
  },

  // === Purification School ===
  {
    id: 'divine_purify_water',
    name: 'Sanctify Water',
    paradigmId: 'divine',
    technique: 'enhance',
    form: 'body',
    source: 'divine',
    manaCost: 15,
    castTime: 30,
    range: 5,
    effectId: 'heal_effect',
    description: 'Render water safe and pure. Contaminants don\'t vanish—they transform into harmless sediment that settles at the bottom. The water itself gains a faint shimmer, the visual equivalent of "blessed by management." Tastes slightly better than normal. Theologians debate whether this is placebo or genuine divine enhancement.',
    school: 'purification',
    baseMishapChance: 0.02,
    hotkeyable: true,
    icon: '💧',
    tags: ['divine', 'utility', 'purification'],
    creatorDetection: {
      detectionRisk: 'undetectable',
      powerLevel: 2,
      leavesMagicalSignature: false,
      detectionNotes: 'Water purification - basic divine utility, indistinguishable from natural processes',
    },
  },
  {
    id: 'divine_consecrate_ground',
    name: 'Consecration',
    paradigmId: 'divine',
    technique: 'enhance',
    form: 'spirit',
    source: 'divine',
    manaCost: 80,
    castTime: 300,
    range: 15,
    duration: -1, // Permanent until dispelled
    effectId: 'major_shield_effect',
    description: 'Declare an area sacred to your deity. The ground becomes holy—not metaphorically, but in ways that affect local reality. Undead feel uncomfortable. Fiends avoid it. The faithful gain subtle benefits. Desecrating consecrated ground requires significant effort and is considered extremely rude.',
    school: 'purification',
    baseMishapChance: 0.12,
    hotkeyable: false,
    icon: '⛪',
    tags: ['divine', 'area', 'permanent', 'holy'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 6,
      leavesMagicalSignature: true,
      detectionNotes: 'Holy ground creation - permanent but legitimate divine territory marking',
    },
  },
  {
    id: 'divine_remove_curse',
    name: 'Unbinding Grace',
    paradigmId: 'divine',
    technique: 'enhance',
    form: 'spirit',
    source: 'divine',
    manaCost: 65,
    castTime: 120,
    range: 1,
    effectId: 'heal_effect',
    description: 'Curses are, essentially, persistent negative contracts with reality. You petition your deity to void the contract. Simple curses dissolve immediately. Complex ones require negotiation. Ancient curses sometimes have divine legal teams and counterclaim for breach of cosmic contract.',
    school: 'purification',
    baseMishapChance: 0.14,
    hotkeyable: false,
    icon: '🔓',
    tags: ['divine', 'curse', 'dispel'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 5,
      leavesMagicalSignature: true,
      detectionNotes: 'Divine contract voiding - proper use of deity authority to correct cosmic wrongs',
    },
  },
];

// ============================================================================
// ACADEMIC PARADIGM SPELLS - Formal Study and Systematic Magic
// ============================================================================

export const ACADEMIC_SPELLS: SpellDefinition[] = [
  // === Evocation - Fire ===
  {
    id: 'academic_ignite',
    name: 'Ignite',
    paradigmId: 'academic',
    technique: 'create',
    form: 'fire',
    source: 'arcane',
    manaCost: 5,
    castTime: 10,
    range: 10,
    effectId: 'ignite_effect',
    description: 'Create a small flame. Your first real spell, and it\'s delightfully simple: channel mana into heat, concentrate it at a point, watch combustion happen. Every wizard remembers their first Ignite—usually because they set something on fire that wasn\'t supposed to burn.',
    school: 'evocation',
    baseMishapChance: 0.05,
    hotkeyable: true,
    icon: '🔥',
    tags: ['fire', 'damage', 'basic'],
    creatorDetection: {
      detectionRisk: 'high',
      forbiddenCategories: ['academic_study'],
      powerLevel: 2,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Even basic spells from systematic study draw creator attention',
    },
  },
  {
    id: 'academic_firebolt',
    name: 'Fire Bolt',
    paradigmId: 'academic',
    technique: 'create',
    form: 'fire',
    source: 'arcane',
    manaCost: 15,
    castTime: 20,
    range: 15,
    effectId: 'ignite_effect',
    description: 'Project flame at a target. Ignite, but with trajectory. You\'re essentially throwing heat—not physically hurling fire, but convincing reality that fire should exist over there instead of here. Distance introduces complications. Wind exists. Targets move. Advanced students learn to compensate.',
    school: 'evocation',
    baseMishapChance: 0.06,
    hotkeyable: true,
    icon: '🔥',
    tags: ['fire', 'damage', 'ranged'],
    prerequisites: ['academic_ignite'],
    creatorDetection: {
      detectionRisk: 'high',
      forbiddenCategories: ['academic_study'],
      powerLevel: 3,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Systematic projectile magic - clear evidence of magical training',
    },
  },
  {
    id: 'academic_fireball',
    name: 'Fireball',
    paradigmId: 'academic',
    technique: 'create',
    form: 'fire',
    source: 'arcane',
    manaCost: 45,
    castTime: 40,
    range: 20,
    effectId: 'fireball_effect',
    description: 'The classic. Every wizard\'s favorite. Create a sphere of concentrated fire and hurl it at your enemies. It explodes on impact, because fire, when compressed enough, has opinions about being compressed. Academies teach Fireball in year three. Rebuilding what students destroy takes year four.',
    school: 'evocation',
    baseMishapChance: 0.15,
    hotkeyable: true,
    icon: '💥',
    prerequisites: ['academic_firebolt'],
    tags: ['fire', 'damage', 'aoe'],
    creatorDetection: {
      detectionRisk: 'critical',
      forbiddenCategories: ['academic_study', 'mass_destruction'],
      powerLevel: 5,
      leavesMagicalSignature: true,
      detectionNotes: 'FORBIDDEN: Classic academic spell with mass destruction potential - immediate intervention',
    },
  },
  {
    id: 'academic_flame_wall',
    name: 'Wall of Flames',
    paradigmId: 'academic',
    technique: 'create',
    form: 'fire',
    source: 'arcane',
    manaCost: 60,
    castTime: 50,
    range: 15,
    duration: 600,
    effectId: 'fireball_effect',
    description: 'Summon a vertical sheet of fire. It hangs in the air, burning nothing but itself, sustained by continuous mana feed. Crossing it is painful but technically possible if you\'re fast and desperate. The wall serves less as absolute barrier and more as "strong suggestion to go another way."',
    school: 'evocation',
    baseMishapChance: 0.12,
    hotkeyable: true,
    icon: '🔥',
    tags: ['fire', 'control', 'area'],
    prerequisites: ['academic_fireball'],
    creatorDetection: {
      detectionRisk: 'critical',
      forbiddenCategories: ['academic_study'],
      powerLevel: 6,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Sustained fire barrier - clear systematic magic application',
    },
  },
  {
    id: 'academic_immolation',
    name: 'Total Immolation',
    paradigmId: 'academic',
    technique: 'create',
    form: 'fire',
    source: 'arcane',
    manaCost: 120,
    castTime: 80,
    range: 25,
    effectId: 'fireball_effect',
    description: 'The theoretical maximum of fire magic: spontaneous, complete combustion of everything in a targeted area. Air ignites. Stone melts. Witnesses report seeing the sun touch ground. The Academy officially forbids teaching this spell, which is exactly why advanced students research it anyway.',
    school: 'evocation',
    baseMishapChance: 0.35,
    hotkeyable: true,
    icon: '☀️',
    tags: ['fire', 'damage', 'legendary', 'dangerous'],
    prerequisites: ['academic_fireball', 'academic_flame_wall'],
    creatorDetection: {
      detectionRisk: 'critical',
      forbiddenCategories: ['academic_study', 'mass_destruction'],
      powerLevel: 9,
      leavesMagicalSignature: true,
      detectionNotes: 'FORBIDDEN: Maximum destructive academic magic - Supreme Creator WILL respond',
    },
  },

  // === Evocation - Ice ===
  {
    id: 'academic_frost_touch',
    name: 'Frost Touch',
    paradigmId: 'academic',
    technique: 'create',
    form: 'body',
    source: 'arcane',
    manaCost: 8,
    castTime: 10,
    range: 1,
    effectId: 'frost_bolt_effect',
    description: 'Freeze what you touch. Thermodynamically questionable—you\'re removing heat faster than radiation alone explains—but it works. Students practice on water. Competent casters freeze enemies\' hands. Master casters create ice sculptures. All equally valid applications of thermal manipulation.',
    school: 'evocation',
    baseMishapChance: 0.04,
    hotkeyable: true,
    icon: '❄️',
    tags: ['ice', 'damage', 'touch'],
    creatorDetection: {
      detectionRisk: 'high',
      forbiddenCategories: ['academic_study'],
      powerLevel: 2,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Basic thermal manipulation from systematic study',
    },
  },
  {
    id: 'academic_frost_bolt',
    name: 'Frost Bolt',
    paradigmId: 'academic',
    technique: 'create',
    form: 'body',
    source: 'arcane',
    manaCost: 20,
    castTime: 25,
    range: 15,
    effectId: 'frost_bolt_effect',
    description: 'Project freezing energy at range. Ice magic, unlike fire, is subtle. No flames, no explosion—just rapid thermal drain. Targets feel cold spreading through them, movement slowing as cellular water crystallizes. Less dramatic than fire. More effective at making people reconsider their choices.',
    school: 'evocation',
    baseMishapChance: 0.08,
    hotkeyable: true,
    icon: '❄️',
    tags: ['ice', 'damage', 'control'],
    prerequisites: ['academic_frost_touch'],
    creatorDetection: {
      detectionRisk: 'high',
      forbiddenCategories: ['academic_study'],
      powerLevel: 3,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Ranged thermal drain - trained spellcaster signature',
    },
  },
  {
    id: 'academic_ice_spear',
    name: 'Glacial Spear',
    paradigmId: 'academic',
    technique: 'create',
    form: 'body',
    source: 'arcane',
    manaCost: 35,
    castTime: 30,
    range: 20,
    effectId: 'frost_bolt_effect',
    description: 'Condense water vapor into a spear of solid ice and hurl it. It\'s both projectile and cold damage—kinetic impact plus thermal drain. The spear shatters on contact, fragments embedding in target. Physics teachers use this as an example of "elegantly efficient violence."',
    school: 'evocation',
    baseMishapChance: 0.11,
    hotkeyable: true,
    icon: '🔷',
    tags: ['ice', 'damage', 'piercing'],
    prerequisites: ['academic_frost_bolt'],
    creatorDetection: {
      detectionRisk: 'high',
      forbiddenCategories: ['academic_study'],
      powerLevel: 4,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Physical ice projectile - clear magical engineering',
    },
  },
  {
    id: 'academic_blizzard',
    name: 'Localized Blizzard',
    paradigmId: 'academic',
    technique: 'create',
    form: 'body',
    source: 'arcane',
    manaCost: 70,
    castTime: 60,
    range: 15,
    duration: 900,
    effectId: 'frost_bolt_effect',
    description: 'Summon winter in a fifteen-foot radius. Wind, snow, plummeting temperature—all the worst parts of a blizzard without requiring actual weather. Inside the effect, visibility drops to inches. Movement becomes treacherous. You, having cast it, know exactly where everything is. Your enemies do not.',
    school: 'evocation',
    baseMishapChance: 0.16,
    hotkeyable: true,
    icon: '🌨️',
    tags: ['ice', 'area', 'control', 'weather'],
    prerequisites: ['academic_ice_spear'],
    creatorDetection: {
      detectionRisk: 'critical',
      forbiddenCategories: ['academic_study'],
      powerLevel: 6,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Localized weather control - sophisticated systematic magic',
    },
  },
  {
    id: 'academic_absolute_zero',
    name: 'Approach Absolute Zero',
    paradigmId: 'academic',
    technique: 'create',
    form: 'body',
    source: 'arcane',
    manaCost: 100,
    castTime: 90,
    range: 10,
    effectId: 'frost_bolt_effect',
    description: 'Drain thermal energy so completely that molecular motion nearly stops. Theoretically impossible—you can\'t actually reach absolute zero—but you can get close enough that the difference stops mattering. Everything in the area becomes brittle as glass. Touch it and it shatters. Beautiful. Horrifying. Very illegal in populated areas.',
    school: 'evocation',
    baseMishapChance: 0.28,
    hotkeyable: true,
    icon: '❄️',
    tags: ['ice', 'damage', 'legendary', 'physics'],
    prerequisites: ['academic_blizzard'],
    creatorDetection: {
      detectionRisk: 'critical',
      forbiddenCategories: ['academic_study', 'reality_warping'],
      powerLevel: 8,
      leavesMagicalSignature: true,
      detectionNotes: 'FORBIDDEN: Physics violation spell - approaching absolute zero warps reality itself',
    },
  },

  // === Evocation - Lightning ===
  {
    id: 'academic_spark',
    name: 'Spark',
    paradigmId: 'academic',
    technique: 'create',
    form: 'spirit',
    source: 'arcane',
    manaCost: 5,
    castTime: 5,
    range: 3,
    effectId: 'lightning_strike_effect',
    description: 'Create a small static discharge. Useful for lighting candles, annoying colleagues, and demonstrating basic principles of electrical magic. The spell every apprentice learns while their teacher explains voltage, current, and why you shouldn\'t practice this in the bath.',
    school: 'evocation',
    baseMishapChance: 0.03,
    hotkeyable: true,
    icon: '⚡',
    tags: ['lightning', 'utility', 'basic'],
    creatorDetection: {
      detectionRisk: 'high',
      forbiddenCategories: ['academic_study'],
      powerLevel: 1,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Basic electrical magic - evidence of formal training',
    },
  },
  {
    id: 'academic_shock',
    name: 'Shocking Grasp',
    paradigmId: 'academic',
    technique: 'create',
    form: 'spirit',
    source: 'arcane',
    manaCost: 12,
    castTime: 10,
    range: 1,
    effectId: 'lightning_strike_effect',
    description: 'Channel electricity through touch. Your hand becomes a live wire. Contact delivers a painful jolt—not enough to kill (usually), but enough to make most people reconsider whatever they were doing. Particularly effective on enemies in metal armor, which becomes unhelpfully conductive.',
    school: 'evocation',
    baseMishapChance: 0.06,
    hotkeyable: true,
    icon: '⚡',
    tags: ['lightning', 'damage', 'touch'],
    prerequisites: ['academic_spark'],
    creatorDetection: {
      detectionRisk: 'high',
      forbiddenCategories: ['academic_study'],
      powerLevel: 2,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Contact electrical discharge - systematic application',
    },
  },
  {
    id: 'academic_lightning_bolt',
    name: 'Lightning Bolt',
    paradigmId: 'academic',
    technique: 'create',
    form: 'spirit',
    source: 'arcane',
    manaCost: 35,
    castTime: 30,
    range: 25,
    effectId: 'lightning_strike_effect',
    description: 'Call down lightning. Not metaphorical lightning—actual electrical discharge. You create a potential difference so extreme that reality responds with a bolt. Instantaneous. Loud. Leaves a smell of ozone and singed regrets. The spell that makes you feel like a storm god, at least for a moment.',
    school: 'evocation',
    baseMishapChance: 0.12,
    hotkeyable: true,
    icon: '⚡',
    tags: ['lightning', 'damage', 'instant'],
    prerequisites: ['academic_shock'],
    creatorDetection: {
      detectionRisk: 'high',
      forbiddenCategories: ['academic_study'],
      powerLevel: 4,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Calling lightning - unnatural weather manipulation',
    },
  },
  {
    id: 'academic_chain_lightning',
    name: 'Chain Lightning',
    paradigmId: 'academic',
    technique: 'create',
    form: 'spirit',
    source: 'arcane',
    manaCost: 65,
    castTime: 45,
    range: 20,
    effectId: 'lightning_strike_effect',
    description: 'Lightning that jumps between targets. You provide the initial bolt; physics handles distribution. Current seeks the path of least resistance, which usually means "the next closest enemy." Each jump weakens the charge, but three or four targets still receive attention. Extremely satisfying against groups.',
    school: 'evocation',
    baseMishapChance: 0.18,
    hotkeyable: true,
    icon: '⚡',
    tags: ['lightning', 'damage', 'chain', 'area'],
    prerequisites: ['academic_lightning_bolt'],
    creatorDetection: {
      detectionRisk: 'critical',
      forbiddenCategories: ['academic_study', 'mass_destruction'],
      powerLevel: 6,
      leavesMagicalSignature: true,
      detectionNotes: 'FORBIDDEN: Multi-target lightning - mass destruction potential',
    },
  },
  {
    id: 'academic_call_storm',
    name: 'Call the Storm',
    paradigmId: 'academic',
    technique: 'create',
    form: 'spirit',
    source: 'arcane',
    manaCost: 110,
    castTime: 120,
    range: 50,
    duration: 1800,
    effectId: 'lightning_strike_effect',
    description: 'Summon an actual storm. Clouds gather. Wind rises. Rain falls. Lightning strikes wherever you direct it, which is as close to godhood as mortal magic gets. The storm persists for half an hour, weather permitting. Local meteorologists despise this spell. Farmers have mixed feelings.',
    school: 'evocation',
    baseMishapChance: 0.25,
    hotkeyable: false,
    icon: '🌩️',
    tags: ['lightning', 'weather', 'area', 'legendary'],
    prerequisites: ['academic_chain_lightning'],
    creatorDetection: {
      detectionRisk: 'critical',
      forbiddenCategories: ['academic_study', 'mass_destruction'],
      powerLevel: 8,
      leavesMagicalSignature: true,
      detectionNotes: 'FORBIDDEN: Summoning actual storms - playing god with weather itself',
    },
  },

  // === Transmutation ===
  {
    id: 'academic_mend',
    name: 'Mend',
    paradigmId: 'academic',
    technique: 'enhance',
    form: 'body',
    source: 'arcane',
    manaCost: 8,
    castTime: 30,
    range: 1,
    effectId: 'heal_effect',
    description: 'Repair small breaks in inanimate objects. You\'re not fixing them—you\'re convincing them to remember being whole and return to that state. Works on torn cloth, cracked pottery, snapped wood. The repair is real, permanent, and often leaves no seam. Your mother would be so proud.',
    school: 'transmutation',
    baseMishapChance: 0.02,
    hotkeyable: true,
    icon: '🔧',
    tags: ['transmutation', 'utility', 'repair'],
    creatorDetection: {
      detectionRisk: 'high',
      forbiddenCategories: ['academic_study'],
      powerLevel: 2,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Matter manipulation - evidence of formal transmutation training',
    },
  },
  {
    id: 'academic_shape_stone',
    name: 'Shape Stone',
    paradigmId: 'academic',
    technique: 'enhance',
    form: 'body',
    source: 'arcane',
    manaCost: 25,
    castTime: 60,
    range: 5,
    effectId: 'heal_effect',
    description: 'Mold stone like clay. The rock becomes temporarily plastic—not liquid, just... compliant. You have about a minute to shape it before molecular structure reasserts itself. Sculptors use this for art. Practical wizards use it for making doors where there weren\'t doors before.',
    school: 'transmutation',
    baseMishapChance: 0.07,
    hotkeyable: true,
    icon: '🗿',
    tags: ['transmutation', 'utility', 'earth'],
    creatorDetection: {
      detectionRisk: 'high',
      forbiddenCategories: ['academic_study'],
      powerLevel: 3,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Stone shaping - advanced material manipulation',
    },
  },
  {
    id: 'academic_transmute_minor',
    name: 'Minor Transmutation',
    paradigmId: 'academic',
    technique: 'enhance',
    form: 'body',
    source: 'arcane',
    manaCost: 40,
    castTime: 90,
    range: 1,
    duration: 3600,
    effectId: 'heal_effect',
    description: 'Change one substance into a similar substance. Wood to stone. Iron to copper. Water to wine, if you\'re feeling biblical. The effect is temporary—an hour, maybe—and you can\'t violate conservation of mass. But for that hour, you\'ve convinced reality that this is, in fact, that.',
    school: 'transmutation',
    baseMishapChance: 0.12,
    hotkeyable: false,
    icon: '🔄',
    tags: ['transmutation', 'utility', 'alchemy'],
    creatorDetection: {
      detectionRisk: 'high',
      forbiddenCategories: ['academic_study'],
      powerLevel: 4,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Substance transmutation - classic alchemy, highly forbidden',
    },
  },
  {
    id: 'academic_enlarge',
    name: 'Enlargement',
    paradigmId: 'academic',
    technique: 'enhance',
    form: 'body',
    source: 'arcane',
    manaCost: 35,
    castTime: 40,
    range: 5,
    duration: 600,
    effectId: 'heal_effect',
    description: 'Make something bigger. The target doubles in size, which means eight times the mass—physics makes this complicated. Clothes stretch. Strength increases proportionally. The spell ends after ten minutes, at which point shrinking back happens suddenly and is reportedly "deeply uncomfortable."',
    school: 'transmutation',
    baseMishapChance: 0.09,
    hotkeyable: true,
    icon: '📏',
    tags: ['transmutation', 'buff', 'size'],
    creatorDetection: {
      detectionRisk: 'high',
      forbiddenCategories: ['academic_study'],
      powerLevel: 4,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Size manipulation - defying physics through systematic magic',
    },
  },
  {
    id: 'academic_polymorph',
    name: 'Polymorph',
    paradigmId: 'academic',
    technique: 'enhance',
    form: 'body',
    source: 'arcane',
    manaCost: 85,
    castTime: 90,
    range: 10,
    duration: 1800,
    effectId: 'heal_effect',
    description: 'Transform a creature into a different creature. This is the big one—the spell that makes your teacher warn about "playing god." The target\'s mind stays intact; their body becomes something else entirely. Sheep are traditional. Half an hour later, they\'re themselves again, traumatized but educated.',
    school: 'transmutation',
    baseMishapChance: 0.22,
    hotkeyable: false,
    icon: '🐑',
    tags: ['transmutation', 'control', 'shapeshift', 'advanced'],
    creatorDetection: {
      detectionRisk: 'critical',
      forbiddenCategories: ['academic_study', 'reality_warping'],
      powerLevel: 7,
      leavesMagicalSignature: true,
      detectionNotes: 'FORBIDDEN: Reshaping living beings - playing god with creation itself',
    },
  },

  // === Abjuration - Protection ===
  {
    id: 'academic_shield',
    name: 'Mage Shield',
    paradigmId: 'academic',
    technique: 'protect',
    form: 'body',
    source: 'arcane',
    manaCost: 10,
    castTime: 5,
    range: 0,
    duration: 600,
    effectId: 'minor_ward_effect',
    description: 'Summon a disc of force that floats near you, intercepting blows. It\'s not a physical shield—more like hardened space. Arrows deflect. Swords skid off. The shield moves with you, anticipating danger. This is the spell that lets wizards pretend they don\'t need armor.',
    school: 'abjuration',
    baseMishapChance: 0.02,
    hotkeyable: true,
    icon: '🛡️',
    tags: ['protection', 'defense', 'personal'],
    creatorDetection: {
      detectionRisk: 'high',
      forbiddenCategories: ['academic_study'],
      powerLevel: 2,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Reactive force barrier - evidence of defensive magic training',
    },
  },
  {
    id: 'academic_minor_ward',
    name: 'Minor Ward',
    paradigmId: 'academic',
    technique: 'protect',
    form: 'body',
    source: 'arcane',
    manaCost: 15,
    castTime: 20,
    range: 0,
    duration: 6000,
    effectId: 'minor_ward_effect',
    description: 'Create a light protective barrier around yourself. Think of it as magical bubble wrap: it absorbs small impacts, deflects minor hazards, makes you generally harder to hurt. Won\'t stop a sword, but it might turn a killing blow into merely terrible.',
    school: 'abjuration',
    baseMishapChance: 0.03,
    hotkeyable: true,
    icon: '🛡️',
    tags: ['protection', 'defense', 'duration'],
    creatorDetection: {
      detectionRisk: 'high',
      forbiddenCategories: ['academic_study'],
      powerLevel: 3,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Sustained protective ward - systematic defensive application',
    },
  },
  {
    id: 'academic_major_shield',
    name: 'Major Shield',
    paradigmId: 'academic',
    technique: 'protect',
    form: 'body',
    source: 'arcane',
    manaCost: 40,
    castTime: 50,
    range: 1,
    duration: 3600,
    effectId: 'major_shield_effect',
    description: 'Create a powerful protective shield. This is Minor Ward\'s ambitious older sibling—thicker barrier, longer duration, better coverage. You could walk through a battlefield with this and emerge annoyed but unharmed. Arrows bounce. Spells dissipate. Swords ring uselessly.',
    school: 'abjuration',
    baseMishapChance: 0.1,
    hotkeyable: true,
    icon: '🛡️',
    prerequisites: ['academic_minor_ward'],
    tags: ['protection', 'defense', 'duration'],
    creatorDetection: {
      detectionRisk: 'high',
      forbiddenCategories: ['academic_study'],
      powerLevel: 4,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Enhanced warding - advanced protective techniques',
    },
  },
  {
    id: 'academic_dispel_magic',
    name: 'Dispel Magic',
    paradigmId: 'academic',
    technique: 'protect',
    form: 'spirit',
    source: 'arcane',
    manaCost: 30,
    castTime: 30,
    range: 15,
    effectId: 'heal_effect',
    description: 'Unravel another mage\'s spell. You\'re essentially untying magical knots—pulling apart the structure until it collapses. Simple spells dissolve easily. Complex ones resist. Ancient enchantments sometimes have the magical equivalent of security systems. Still, when it works, watching your enemy\'s magic simply stop is deeply satisfying.',
    school: 'abjuration',
    baseMishapChance: 0.08,
    hotkeyable: true,
    icon: '🚫',
    tags: ['protection', 'dispel', 'counter'],
    creatorDetection: {
      detectionRisk: 'critical',
      forbiddenCategories: ['academic_study'],
      powerLevel: 4,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Counter-magic - understanding magical structure is deeply forbidden',
    },
  },
  {
    id: 'academic_counterspell',
    name: 'Counterspell',
    paradigmId: 'academic',
    technique: 'protect',
    form: 'spirit',
    source: 'arcane',
    manaCost: 25,
    castTime: 1,
    range: 20,
    effectId: 'heal_effect',
    description: 'Interrupt a spell as it\'s being cast. You identify the structure mid-formation and inject chaos at exactly the right moment. The enemy spell collapses. Their mana wastes. You smile smugly. This is the spell that makes wizard duels interesting—when neither side can complete their favorite techniques.',
    school: 'abjuration',
    baseMishapChance: 0.15,
    hotkeyable: true,
    icon: '⛔',
    tags: ['protection', 'counter', 'instant'],
    creatorDetection: {
      detectionRisk: 'critical',
      forbiddenCategories: ['academic_study'],
      powerLevel: 5,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Spell interruption - directly countering magic requires deep systematic knowledge',
    },
  },
  {
    id: 'academic_antimagic_field',
    name: 'Antimagic Field',
    paradigmId: 'academic',
    technique: 'protect',
    form: 'spirit',
    source: 'arcane',
    manaCost: 95,
    castTime: 90,
    range: 10,
    duration: 600,
    effectId: 'major_shield_effect',
    description: 'Create a zone where magic simply doesn\'t work. No spells in. No spells out. Existing enchantments suppress. It\'s the magical equivalent of a dead zone—reality enforcing mundane physics only. Inside, wizards are just people with pointy hats and expensive education. Humbling. Sometimes necessary.',
    school: 'abjuration',
    baseMishapChance: 0.20,
    hotkeyable: false,
    icon: '🚫',
    tags: ['protection', 'antimagic', 'area', 'legendary'],
    creatorDetection: {
      detectionRisk: 'critical',
      forbiddenCategories: ['academic_study', 'reality_warping'],
      powerLevel: 8,
      leavesMagicalSignature: true,
      detectionNotes: 'FORBIDDEN: Nullifying magic itself - supreme understanding of magical theory',
    },
  },

  // === Illusion ===
  {
    id: 'academic_ghost_sound',
    name: 'Phantom Sound',
    paradigmId: 'academic',
    technique: 'create',
    form: 'spirit',
    source: 'arcane',
    manaCost: 6,
    castTime: 10,
    range: 15,
    duration: 60,
    effectId: 'heal_effect',
    description: 'Create illusory sound. Voices. Footsteps. Screaming. Whatever you imagine. The sound is real—air actually vibrates—but the source is fictional. Useful for distraction, misdirection, and convincing people there\'s someone else in the room. The first spell of every competent liar.',
    school: 'illusion',
    baseMishapChance: 0.03,
    hotkeyable: true,
    icon: '🔊',
    tags: ['illusion', 'sound', 'utility'],
    creatorDetection: {
      detectionRisk: 'high',
      forbiddenCategories: ['academic_study'],
      powerLevel: 2,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Sound fabrication - basic deception magic training',
    },
  },
  {
    id: 'academic_minor_illusion',
    name: 'Minor Illusion',
    paradigmId: 'academic',
    technique: 'create',
    form: 'spirit',
    source: 'arcane',
    manaCost: 10,
    castTime: 15,
    range: 10,
    duration: 600,
    effectId: 'heal_effect',
    description: 'Create a simple visual illusion. A chair that isn\'t there. A door where there\'s wall. The image is static—no movement—and breaks if touched. But for pure "make people see something false," this is your entry point. Apprentices practice by hiding their spell components from teachers.',
    school: 'illusion',
    baseMishapChance: 0.04,
    hotkeyable: true,
    icon: '👁️',
    tags: ['illusion', 'visual', 'static'],
    creatorDetection: {
      detectionRisk: 'high',
      forbiddenCategories: ['academic_study'],
      powerLevel: 2,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Visual illusion - academic light manipulation',
    },
  },
  {
    id: 'academic_invisibility',
    name: 'Invisibility',
    paradigmId: 'academic',
    technique: 'enhance',
    form: 'spirit',
    source: 'arcane',
    manaCost: 35,
    castTime: 40,
    range: 1,
    duration: 600,
    effectId: 'heal_effect',
    description: 'Bend light around the target until they can\'t be seen. Not actual transparency—the matter\'s still there—but perfect optical camouflage. Ten minutes of being unseen. Ends if you attack someone, which is fair. Invisible assassins would be unreasonably overpowered, even by wizard standards.',
    school: 'illusion',
    baseMishapChance: 0.09,
    hotkeyable: true,
    icon: '👻',
    tags: ['illusion', 'stealth', 'buff'],
    prerequisites: ['academic_minor_illusion'],
    creatorDetection: {
      detectionRisk: 'high',
      forbiddenCategories: ['academic_study'],
      powerLevel: 4,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Light bending - advanced optical manipulation',
    },
  },
  {
    id: 'academic_major_illusion',
    name: 'Major Illusion',
    paradigmId: 'academic',
    technique: 'create',
    form: 'spirit',
    source: 'arcane',
    manaCost: 45,
    castTime: 60,
    range: 20,
    duration: 1800,
    effectId: 'heal_effect',
    description: 'Create a complex, moving illusion. People, creatures, landscapes—anything visual and auditory. The illusion responds to your mental direction, moves naturally, seems real. Touch still breaks it, but from a distance, it\'s indistinguishable from reality. The spell that makes reality optional.',
    school: 'illusion',
    baseMishapChance: 0.12,
    hotkeyable: false,
    icon: '🎭',
    tags: ['illusion', 'complex', 'interactive'],
    prerequisites: ['academic_minor_illusion'],
    creatorDetection: {
      detectionRisk: 'high',
      forbiddenCategories: ['academic_study'],
      powerLevel: 5,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Complex illusion - sophisticated sensory manipulation',
    },
  },
  {
    id: 'academic_phantasmal_killer',
    name: 'Phantasmal Assassin',
    paradigmId: 'academic',
    technique: 'create',
    form: 'spirit',
    source: 'arcane',
    manaCost: 65,
    castTime: 50,
    range: 15,
    effectId: 'lightning_strike_effect',
    description: 'Create an illusion so terrifying that the target\'s mind makes it real. Only they can see it—their personal nightmare given form. If they believe it can kill them, their body might agree. Psychosomatic damage. Ethically questionable. Horrifyingly effective. The Academy debates banning this spell annually.',
    school: 'illusion',
    baseMishapChance: 0.18,
    hotkeyable: true,
    icon: '💀',
    tags: ['illusion', 'psychic', 'damage', 'fear'],
    prerequisites: ['academic_major_illusion'],
    creatorDetection: {
      detectionRisk: 'critical',
      forbiddenCategories: ['academic_study'],
      powerLevel: 6,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Mind-killing illusion - weaponized psychology, ethically forbidden',
    },
  },

  // === Divination ===
  {
    id: 'academic_detect_magic',
    name: 'Detect Magic',
    paradigmId: 'academic',
    technique: 'perceive',
    form: 'spirit',
    source: 'arcane',
    manaCost: 10,
    castTime: 30,
    range: 30,
    duration: 1200,
    effectId: 'detect_magic_effect',
    description: 'Sense magical auras in the area. Active spells shimmer. Enchanted objects glow faintly. You see the invisible infrastructure of magic that pervades everything. It\'s like developing new senses—suddenly the world is full of light only you can see. First-time casters often report feeling "less alone."',
    school: 'divination',
    baseMishapChance: 0.02,
    hotkeyable: true,
    icon: '👁️',
    tags: ['detection', 'utility'],
    creatorDetection: {
      detectionRisk: 'critical',
      forbiddenCategories: ['academic_study'],
      powerLevel: 3,
      leavesMagicalSignature: true,
      detectionNotes: 'FORBIDDEN: Perceiving magic itself - studying the structure of reality is deeply forbidden',
    },
  },
  {
    id: 'academic_identify',
    name: 'Identify Enchantment',
    paradigmId: 'academic',
    technique: 'perceive',
    form: 'spirit',
    source: 'arcane',
    manaCost: 25,
    castTime: 60,
    range: 1,
    effectId: 'detect_magic_effect',
    description: 'Understand what a magical item does. You examine the enchantment\'s structure, trace its patterns, read its purpose like text. Simple items reveal themselves immediately. Complex artifacts require interpretation. Ancient relics sometimes respond poorly to unauthorized analysis. Still, usually worth the risk.',
    school: 'divination',
    baseMishapChance: 0.07,
    hotkeyable: false,
    icon: '🔍',
    tags: ['detection', 'utility', 'analysis'],
    creatorDetection: {
      detectionRisk: 'critical',
      forbiddenCategories: ['academic_study'],
      powerLevel: 4,
      leavesMagicalSignature: true,
      detectionNotes: 'FORBIDDEN: Analyzing enchantments - understanding magical theory is deeply forbidden',
    },
  },
  {
    id: 'academic_clairvoyance',
    name: 'Clairvoyance',
    paradigmId: 'academic',
    technique: 'perceive',
    form: 'spirit',
    source: 'arcane',
    manaCost: 50,
    castTime: 90,
    range: 1000,
    duration: 600,
    effectId: 'detect_magic_effect',
    description: 'See a distant location as if you were there. You create an invisible sensor—a point of perception—and route its input to your mind. See through walls. Scout ahead. Spy on conversations. Deeply useful. Thoroughly invasive. Illegal in most civilized nations without a warrant.',
    school: 'divination',
    baseMishapChance: 0.11,
    hotkeyable: false,
    icon: '🔮',
    tags: ['detection', 'scrying', 'remote'],
    creatorDetection: {
      detectionRisk: 'critical',
      forbiddenCategories: ['academic_study'],
      powerLevel: 5,
      leavesMagicalSignature: true,
      detectionNotes: 'FORBIDDEN: Remote viewing - invasive perception magic, highly detectable',
    },
  },

  // === Healing ===
  {
    id: 'academic_heal',
    name: 'Heal Wounds',
    paradigmId: 'academic',
    technique: 'enhance',
    form: 'body',
    source: 'arcane',
    manaCost: 30,
    castTime: 60,
    range: 1,
    effectId: 'heal_effect',
    description: 'Accelerate natural healing in a target. You\'re not divine—you can\'t perform miracles—but you can convince cells to repair faster. Wounds close. Bones knit. The body does what it normally does, just much quicker. Academic healing lacks divine grace but makes up for it with reliable, reproducible results.',
    school: 'restoration',
    baseMishapChance: 0.1,
    hotkeyable: true,
    icon: '💚',
    tags: ['healing', 'support'],
    creatorDetection: {
      detectionRisk: 'high',
      forbiddenCategories: ['academic_study'],
      powerLevel: 4,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Systematic healing - learned medicine-magic',
    },
  },
  {
    id: 'academic_regeneration',
    name: 'Regeneration',
    paradigmId: 'academic',
    technique: 'enhance',
    form: 'body',
    source: 'arcane',
    manaCost: 20,
    castTime: 40,
    range: 1,
    duration: 600,
    effectId: 'regeneration_effect',
    description: 'Grant gradual health regeneration over time. For the next ten minutes, the target heals continuously—slowly, but steadily. Minor wounds close completely. Major ones improve significantly. It\'s maintenance healing: keeping people alive through prolonged danger rather than dramatic recovery.',
    school: 'restoration',
    baseMishapChance: 0.05,
    hotkeyable: true,
    icon: '💗',
    tags: ['healing', 'support', 'duration'],
    creatorDetection: {
      detectionRisk: 'high',
      forbiddenCategories: ['academic_study'],
      powerLevel: 3,
      leavesMagicalSignature: true,
      detectionNotes: 'ACADEMIC MAGIC: Sustained healing - systematic biological magic',
    },
  },
];

// ============================================================================
// BLOOD PARADIGM SPELLS - Hemomancy, Vitality, and Sacrifice
// ============================================================================

export const BLOOD_SPELLS: SpellDefinition[] = [
  // === Hemomancy - Blood as Fuel ===
  {
    id: 'blood_sacrifice_minor',
    name: 'Lesser Blood Offering',
    paradigmId: 'blood',
    technique: 'create',
    form: 'body',
    source: 'blood',
    manaCost: 0, // Costs health instead
    castTime: 20,
    range: 0,
    effectId: 'heal_effect',
    description: 'Pay in blood for power. You open a small cut—nothing dramatic, just enough to matter—and the magic responds. Blood has memory. Blood has weight. The universe accepts it as currency. This is the fundamental exchange: your vitality for immediate effect. The cut heals, but the cost remains.',
    school: 'hemomancy',
    baseMishapChance: 0.08,
    hotkeyable: true,
    icon: '🩸',
    tags: ['blood', 'sacrifice', 'cost'],
    creatorDetection: {
      detectionRisk: 'high',
      powerLevel: 3,
      leavesMagicalSignature: true,
      detectionNotes: 'Blood magic: Life force sacrifice - draws attention through vitality manipulation',
    },
  },
  {
    id: 'blood_bolt',
    name: 'Crimson Bolt',
    paradigmId: 'blood',
    technique: 'create',
    form: 'body',
    source: 'blood',
    manaCost: 0,
    castTime: 15,
    range: 15,
    effectId: 'ignite_effect',
    description: 'Shape your blood into a projectile. It leaves your body as liquid and hardens mid-flight into something like glass—sharp, fast, deeply personal. The bolt carries a fragment of your life force. Hits harder than it should. Leaves enemies unsettled in ways normal weapons don\'t.',
    school: 'hemomancy',
    baseMishapChance: 0.10,
    hotkeyable: true,
    icon: '🩸',
    tags: ['blood', 'damage', 'projectile'],
    creatorDetection: {
      detectionRisk: 'high',
      powerLevel: 3,
      leavesMagicalSignature: true,
      detectionNotes: 'Blood magic: Weaponized blood - life force converted to damage',
    },
  },
  {
    id: 'blood_bond',
    name: 'Sanguine Link',
    paradigmId: 'blood',
    technique: 'enhance',
    form: 'body',
    source: 'blood',
    manaCost: 0,
    castTime: 60,
    range: 5,
    duration: 3600,
    effectId: 'heal_effect',
    description: 'Mingle your blood with another\'s. For the next hour, you share wounds—damage to either distributes between both. Useful for protecting the fragile. Terrifying when you realize your enemy can hurt you by hurting themselves. Blood bonds are intimate magic, whether you want them to be or not.',
    school: 'binding',
    baseMishapChance: 0.12,
    hotkeyable: false,
    icon: '🔗',
    tags: ['blood', 'bond', 'sharing'],
    creatorDetection: {
      detectionRisk: 'high',
      powerLevel: 4,
      leavesMagicalSignature: true,
      detectionNotes: 'Blood magic: Life-binding - connecting vital energies is noticeable',
    },
  },
  {
    id: 'blood_puppet',
    name: 'Crimson Strings',
    paradigmId: 'blood',
    technique: 'create',
    form: 'body',
    source: 'blood',
    manaCost: 0,
    castTime: 40,
    range: 10,
    duration: 300,
    effectId: 'lightning_strike_effect',
    description: 'Control someone through their blood. You don\'t possess their mind—that\'s different magic—but you can pull their limbs, force movement, make the body betray its owner. Deeply unpleasant for everyone involved. The kind of spell that gets you banned from civilized society. Works beautifully.',
    school: 'hemomancy',
    baseMishapChance: 0.25,
    hotkeyable: false,
    icon: '🎭',
    tags: ['blood', 'control', 'forbidden'],
    creatorDetection: {
      detectionRisk: 'critical',
      powerLevel: 6,
      leavesMagicalSignature: true,
      detectionNotes: 'FORBIDDEN: Blood puppet - controlling beings through their blood violates bodily autonomy',
    },
  },
  {
    id: 'blood_heal_transfer',
    name: 'Vitality Transfer',
    paradigmId: 'blood',
    technique: 'enhance',
    form: 'body',
    source: 'blood',
    manaCost: 0,
    castTime: 30,
    range: 1,
    effectId: 'heal_effect',
    description: 'Take someone\'s wounds into yourself. Their injuries close; yours open. The damage doesn\'t vanish—conservation of suffering—but it redistributes. Profoundly useful. Possibly heroic. Definitely hurts. Blood mages report this is either the kindest or cruelest spell they know, depending on context.',
    school: 'hemomancy',
    baseMishapChance: 0.15,
    hotkeyable: true,
    icon: '💉',
    tags: ['blood', 'healing', 'transfer'],
    creatorDetection: {
      detectionRisk: 'high',
      powerLevel: 4,
      leavesMagicalSignature: true,
      detectionNotes: 'Blood magic: Wound transfer - heroic self-sacrifice, somewhat less suspicious',
    },
  },
  {
    id: 'blood_boil',
    name: 'Boiling Blood',
    paradigmId: 'blood',
    technique: 'create',
    form: 'body',
    source: 'blood',
    manaCost: 0,
    castTime: 35,
    range: 12,
    effectId: 'fireball_effect',
    description: 'Raise the temperature of someone\'s blood. Not metaphorically—literally heating hemoglobin until it bubbles. The target feels fever spike into agony. Most lose consciousness within seconds. Mortality rate is high. This is the spell that makes people understand why blood magic is feared.',
    school: 'hemomancy',
    baseMishapChance: 0.30,
    hotkeyable: true,
    icon: '🌡️',
    tags: ['blood', 'damage', 'lethal', 'feared'],
    creatorDetection: {
      detectionRisk: 'critical',
      forbiddenCategories: ['mass_destruction'],
      powerLevel: 7,
      leavesMagicalSignature: true,
      detectionNotes: 'FORBIDDEN: Blood boiling - horrific attack spell, Supreme Creator disapproves strongly',
    },
  },
  {
    id: 'blood_scrying',
    name: 'Trace the Bloodline',
    paradigmId: 'blood',
    technique: 'perceive',
    form: 'spirit',
    source: 'blood',
    manaCost: 0,
    castTime: 90,
    range: 1000,
    duration: 600,
    effectId: 'detect_magic_effect',
    description: 'Find someone through blood connection. Given a sample—a drop, a smear—you trace back to its source. Blood knows where it came from. You follow that knowledge across any distance. Privacy laws hate this spell. Detectives love it. Everyone agrees it\'s uncomfortably effective.',
    school: 'divination',
    baseMishapChance: 0.14,
    hotkeyable: false,
    icon: '🔍',
    tags: ['blood', 'tracking', 'divination'],
    creatorDetection: {
      detectionRisk: 'high',
      powerLevel: 5,
      leavesMagicalSignature: true,
      detectionNotes: 'Blood magic: Bloodline tracking - invasive but not forbidden',
    },
  },

  // === Vitality Manipulation ===
  {
    id: 'blood_strengthen',
    name: 'Surge of Vitality',
    paradigmId: 'blood',
    technique: 'enhance',
    form: 'body',
    source: 'blood',
    manaCost: 0,
    castTime: 20,
    range: 0,
    duration: 300,
    effectId: 'heal_effect',
    description: 'Burn your life force for temporary strength. Muscles swell. Reflexes sharpen. You become briefly superhuman by converting longevity into immediate capability. The effect fades after five minutes. You\'ll feel it later—exhaustion, accelerated aging, the bill coming due. Worth it in emergencies.',
    school: 'vitality',
    baseMishapChance: 0.10,
    hotkeyable: true,
    icon: '💪',
    tags: ['blood', 'buff', 'strength'],
    creatorDetection: {
      detectionRisk: 'high',
      powerLevel: 4,
      leavesMagicalSignature: true,
      detectionNotes: 'Blood magic: Vitality surge - burning life for power',
    },
  },
  {
    id: 'blood_regenerate',
    name: 'Forced Regeneration',
    paradigmId: 'blood',
    technique: 'enhance',
    form: 'body',
    source: 'blood',
    manaCost: 0,
    castTime: 40,
    range: 0,
    duration: 600,
    effectId: 'regeneration_effect',
    description: 'Accelerate your healing to unnatural rates. Wounds close in seconds. Broken bones set themselves. You\'re burning through vitality reserves normally saved for decades of life. Ten minutes of regeneration might cost weeks off your lifespan. The math is unfavorable but the alternative is death.',
    school: 'vitality',
    baseMishapChance: 0.18,
    hotkeyable: true,
    icon: '🩹',
    tags: ['blood', 'healing', 'regeneration'],
    creatorDetection: {
      detectionRisk: 'high',
      powerLevel: 5,
      leavesMagicalSignature: true,
      detectionNotes: 'Blood magic: Accelerated regeneration - burning years for minutes',
    },
  },
  {
    id: 'blood_drain',
    name: 'Vampiric Touch',
    paradigmId: 'blood',
    technique: 'create',
    form: 'body',
    source: 'blood',
    manaCost: 0,
    castTime: 25,
    range: 1,
    effectId: 'heal_effect',
    description: 'Steal life force through contact. Your touch draws vitality from the target into yourself. Their wounds become your healing. Their exhaustion becomes your energy. Technically not vampirism—you\'re not drinking blood—but the emotional experience is similar. Most targets strongly object.',
    school: 'vitality',
    baseMishapChance: 0.16,
    hotkeyable: true,
    icon: '🧛',
    tags: ['blood', 'drain', 'vampire'],
    creatorDetection: {
      detectionRisk: 'critical',
      powerLevel: 5,
      leavesMagicalSignature: true,
      detectionNotes: 'FORBIDDEN: Vampiric touch - stealing life force from others crosses ethical lines',
    },
  },
];

// ============================================================================
// NAME PARADIGM SPELLS - True Names and the Language of Creation
// ============================================================================

export const NAME_SPELLS: SpellDefinition[] = [
  // === Speaking - Using Names ===
  {
    id: 'name_speak_fire',
    name: 'Speak to Fire',
    paradigmId: 'name',
    technique: 'create',
    form: 'fire',
    source: 'ancestral',
    manaCost: 15,
    castTime: 20,
    range: 10,
    effectId: 'ignite_effect',
    description: 'Say the true name of fire. Not "fire" in human language—the actual name, the word that fire recognizes as itself. Spoken correctly, fire obeys. You don\'t create flames; you call them into being by addressing them directly. They come because you know what to say.',
    school: 'speaking',
    baseMishapChance: 0.06,
    hotkeyable: true,
    icon: '🔥',
    tags: ['name', 'fire', 'command'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 3,
      leavesMagicalSignature: false,
      detectionNotes: 'Name magic: Speaking to elements - ancestral tradition, natural communion',
    },
  },
  {
    id: 'name_command_wind',
    name: 'Command the Wind',
    paradigmId: 'name',
    technique: 'create',
    form: 'spirit',
    source: 'ancestral',
    manaCost: 20,
    castTime: 30,
    range: 20,
    effectId: 'heal_effect',
    description: 'Speak wind\'s name and it listens. Gentle breeze or roaring gale—it depends on your tone. Wind is capricious, more playful than fire, but bound by the same principle: true names compel. You ask nicely in the language of creation and wind, flattered by recognition, complies.',
    school: 'speaking',
    baseMishapChance: 0.08,
    hotkeyable: true,
    icon: '💨',
    tags: ['name', 'wind', 'command'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 3,
      leavesMagicalSignature: false,
      detectionNotes: 'Name magic: Wind speaking - traditional elemental communion',
    },
  },
  {
    id: 'name_bind_spirit',
    name: 'Bind by True Name',
    paradigmId: 'name',
    technique: 'create',
    form: 'spirit',
    source: 'ancestral',
    manaCost: 45,
    castTime: 60,
    range: 15,
    duration: 1800,
    effectId: 'lightning_strike_effect',
    description: 'Know a spirit\'s true name and you own it—not possession, but binding. The name is a leash, a contract written into cosmic fabric. The spirit must obey direct commands for half an hour. Afterward, it remembers. Most spirits find this deeply humiliating and hold impressive grudges.',
    school: 'binding',
    baseMishapChance: 0.20,
    hotkeyable: false,
    icon: '👻',
    tags: ['name', 'binding', 'spirit'],
    creatorDetection: {
      detectionRisk: 'moderate',
      powerLevel: 5,
      leavesMagicalSignature: true,
      detectionNotes: 'Name magic: Spirit binding - compulsion through true names draws some attention',
    },
  },
  {
    id: 'name_speak_stone',
    name: 'Converse with Stone',
    paradigmId: 'name',
    technique: 'enhance',
    form: 'body',
    source: 'ancestral',
    manaCost: 25,
    castTime: 40,
    range: 10,
    effectId: 'heal_effect',
    description: 'Address stone by its true name and it becomes malleable. You\'re not changing it—you\'re asking it to change. Stone is patient, slow, but responsive when spoken to correctly. It flows, reshapes, creates passages. The effect is permanent because you\'ve negotiated with stone itself.',
    school: 'speaking',
    baseMishapChance: 0.10,
    hotkeyable: true,
    icon: '🗿',
    tags: ['name', 'stone', 'shaping'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 3,
      leavesMagicalSignature: false,
      detectionNotes: 'Name magic: Stone negotiation - respectful elemental communion',
    },
  },
  {
    id: 'name_true_strike',
    name: 'Strike True',
    paradigmId: 'name',
    technique: 'enhance',
    form: 'body',
    source: 'ancestral',
    manaCost: 30,
    castTime: 25,
    range: 25,
    effectId: 'lightning_strike_effect',
    description: 'Speak the true name of your target and your attack cannot miss. You\'re not improving aim—you\'re invoking metaphysical certainty. The name creates connection. The weapon follows connection to conclusion. Reality adjusts to make the statement "this hits" factually correct.',
    school: 'speaking',
    baseMishapChance: 0.12,
    hotkeyable: true,
    icon: '🎯',
    tags: ['name', 'accuracy', 'attack'],
    creatorDetection: {
      detectionRisk: 'moderate',
      powerLevel: 4,
      leavesMagicalSignature: true,
      detectionNotes: 'Name magic: True strike - using true names offensively is somewhat noticeable',
    },
  },

  // === Knowing - Learning Names ===
  {
    id: 'name_learn_object',
    name: 'Know the Thing',
    paradigmId: 'name',
    technique: 'perceive',
    form: 'body',
    source: 'ancestral',
    manaCost: 35,
    castTime: 120,
    range: 1,
    effectId: 'detect_magic_effect',
    description: 'Learn an object\'s true name through study. Two minutes of focused attention—touching it, examining it, listening to what it is beneath what it seems. The name emerges as intuition, as knowing without being told. Simple objects have simple names. Ancient artifacts have names like poetry.',
    school: 'knowing',
    baseMishapChance: 0.08,
    hotkeyable: false,
    icon: '📖',
    tags: ['name', 'learning', 'study'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 4,
      leavesMagicalSignature: false,
      detectionNotes: 'Name magic: Object divination - learning names through meditation',
    },
  },
  {
    id: 'name_learn_person',
    name: 'Discern True Name',
    paradigmId: 'name',
    technique: 'perceive',
    form: 'spirit',
    source: 'ancestral',
    manaCost: 60,
    castTime: 300,
    range: 1,
    effectId: 'detect_magic_effect',
    description: 'Learn someone\'s true name. This takes time—conversation, observation, understanding who they really are beneath masks and pretense. When you finally hear it (and you will hear it, silent but certain), you gain power over them. They\'ll know immediately. Trust never quite recovers.',
    school: 'knowing',
    baseMishapChance: 0.25,
    hotkeyable: false,
    icon: '🔍',
    tags: ['name', 'learning', 'power'],
    creatorDetection: {
      detectionRisk: 'moderate',
      powerLevel: 6,
      leavesMagicalSignature: true,
      detectionNotes: 'Name magic: True name divination - gaining power over a person through their name',
    },
  },

  // === Changing - Altering Names ===
  {
    id: 'name_change_self',
    name: 'Rename Yourself',
    paradigmId: 'name',
    technique: 'enhance',
    form: 'spirit',
    source: 'ancestral',
    manaCost: 150,
    castTime: 600,
    range: 0,
    duration: -1,
    effectId: 'heal_effect',
    description: 'Change your own true name. This is profound magic—not identity theft, but identity reformation. You become, at fundamental level, someone else. Old bindings break. Old connections sever. You escape fate, prediction, anyone who knew your old name. The cost is continuity: you\'re no longer quite who you were.',
    school: 'changing',
    baseMishapChance: 0.40,
    hotkeyable: false,
    icon: '🦋',
    tags: ['name', 'transformation', 'legendary'],
    creatorDetection: {
      detectionRisk: 'high',
      powerLevel: 8,
      leavesMagicalSignature: true,
      detectionNotes: 'Name magic: Self-renaming - identity reformation is powerful but personal',
    },
  },
  {
    id: 'name_unmake',
    name: 'Speak Unmaking',
    paradigmId: 'name',
    technique: 'create',
    form: 'spirit',
    source: 'ancestral',
    manaCost: 100,
    castTime: 90,
    range: 15,
    effectId: 'lightning_strike_effect',
    description: 'Say the true name of something backward. This is ontological deletion—not destroying, but asserting nonexistence. The thing hears its name inverted and, confused by the paradox, ceases. Works on objects, magical constructs, occasionally concepts. Living things resist fiercely. Reality finds this spell philosophically troubling.',
    school: 'changing',
    baseMishapChance: 0.35,
    hotkeyable: false,
    icon: '🌀',
    tags: ['name', 'destruction', 'forbidden'],
    creatorDetection: {
      detectionRisk: 'critical',
      forbiddenCategories: ['reality_warping'],
      powerLevel: 9,
      leavesMagicalSignature: true,
      detectionNotes: 'FORBIDDEN: Unmaking - erasing existence through reversed naming warps reality itself',
    },
  },
];

// ============================================================================
// BREATH PARADIGM SPELLS - Awakening and Commands (Animus-inspired)
// ============================================================================

export const BREATH_SPELLS: SpellDefinition[] = [
  // === Basic Awakening ===
  {
    id: 'breath_awaken_rope',
    name: 'Awaken Rope',
    paradigmId: 'breath',
    technique: 'enhance',
    form: 'body',
    source: 'psionic',
    manaCost: 50, // One Breath
    castTime: 30,
    range: 1,
    duration: 600,
    effectId: 'heal_effect',
    description: 'Give rope the breath of life. You invest one Breath—a fragment of your vital essence—and speak a Command. The rope wakes. Moves. Obeys. It\'s not alive, exactly, but animated. Autonomous. When the Breath fades after ten minutes, the rope returns to ordinary cordage, remembering nothing.',
    school: 'awakening',
    baseMishapChance: 0.05,
    hotkeyable: true,
    icon: '🪢',
    tags: ['breath', 'awakening', 'basic'],
    creatorDetection: {
      detectionRisk: 'moderate',
      powerLevel: 3,
      leavesMagicalSignature: true,
      detectionNotes: 'Breath magic: Basic awakening - animating objects through life essence',
    },
  },
  {
    id: 'breath_awaken_cloth',
    name: 'Awaken Cloth',
    paradigmId: 'breath',
    technique: 'enhance',
    form: 'body',
    source: 'psionic',
    manaCost: 50,
    castTime: 35,
    range: 1,
    duration: 600,
    effectId: 'heal_effect',
    description: 'Breathe life into fabric. Cloaks become shields. Tapestries become walls. The cloth moves at your Command—wrapping, protecting, entangling. It drains color as it awakens; brilliant dyes fade to gray as life-force redistributes. The exchange is always visible: magic has aesthetic cost.',
    school: 'awakening',
    baseMishapChance: 0.06,
    hotkeyable: true,
    icon: '🧵',
    tags: ['breath', 'awakening', 'fabric'],
    creatorDetection: {
      detectionRisk: 'moderate',
      powerLevel: 3,
      leavesMagicalSignature: true,
      detectionNotes: 'Breath magic: Cloth awakening - animating fabric through vital breath',
    },
  },
  {
    id: 'breath_awaken_smoke',
    name: 'Awaken Smoke',
    paradigmId: 'breath',
    technique: 'enhance',
    form: 'spirit',
    source: 'psionic',
    manaCost: 100, // Two Breaths
    castTime: 40,
    range: 10,
    duration: 300,
    effectId: 'heal_effect',
    description: 'Grant consciousness to smoke. This is advanced—smoke has no form, no structure, just particles suspended in air. Yet Awakened smoke moves with purpose, obscures specifically, forms shapes on command. Expensive. Beautiful. The kind of magic that makes spectators stop and stare.',
    school: 'awakening',
    baseMishapChance: 0.15,
    hotkeyable: true,
    icon: '💨',
    tags: ['breath', 'awakening', 'smoke'],
    creatorDetection: {
      detectionRisk: 'moderate',
      powerLevel: 4,
      leavesMagicalSignature: true,
      detectionNotes: 'Breath magic: Advanced awakening - animating formless matter',
    },
  },
  {
    id: 'breath_heighten_first',
    name: 'First Pneumantic Tier',
    paradigmId: 'breath',
    technique: 'enhance',
    form: 'body',
    source: 'psionic',
    manaCost: 0, // Passive with 50+ Breaths
    castTime: 0,
    range: 0,
    duration: -1,
    effectId: 'heal_effect',
    description: 'Accumulate fifty Breaths and reality notices. Your aura becomes visible—subtle, but there—radiating vitality. Colors seem brighter near you. People unconsciously defer. This isn\'t a spell you cast; it\'s a state of being. The first step toward something more than human.',
    school: 'pneumantic_tier',
    baseMishapChance: 0.0,
    hotkeyable: false,
    icon: '✨',
    tags: ['breath', 'pneumantic_tier', 'passive'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 2,
      leavesMagicalSignature: false,
      detectionNotes: 'Breath magic: Passive pneumantic_tier - natural accumulation of life force',
    },
  },
  {
    id: 'breath_heighten_second',
    name: 'Second Pneumantic Tier',
    paradigmId: 'breath',
    technique: 'enhance',
    form: 'body',
    source: 'psionic',
    manaCost: 0, // Passive with 200+ Breaths
    castTime: 0,
    range: 0,
    duration: -1,
    effectId: 'heal_effect',
    description: 'Two hundred Breaths grants perfect pitch and color recognition. Your senses sharpen—not superhuman, but perfectly calibrated. You hear harmonics others miss. See color gradations invisible to normal sight. Useful for Awakening, where precision matters. The world becomes more vivid.',
    school: 'pneumantic_tier',
    baseMishapChance: 0.0,
    hotkeyable: false,
    icon: '🎨',
    tags: ['breath', 'pneumantic_tier', 'senses'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 3,
      leavesMagicalSignature: false,
      detectionNotes: 'Breath magic: Passive pneumantic_tier - enhanced perception through accumulated breath',
    },
  },
  {
    id: 'breath_command_protect',
    name: 'Command: Protect Me',
    paradigmId: 'breath',
    technique: 'protect',
    form: 'body',
    source: 'psionic',
    manaCost: 50,
    castTime: 20,
    range: 5,
    duration: 600,
    effectId: 'minor_ward_effect',
    description: 'The fundamental defensive Command. Whatever you\'ve Awakened interposes itself between you and harm. Awakened cloth becomes armor. Awakened rope becomes barrier. The magic is literal-minded—you said "protect," it protects, even at cost of its own destruction.',
    school: 'commands',
    baseMishapChance: 0.04,
    hotkeyable: true,
    icon: '🛡️',
    tags: ['breath', 'command', 'protection'],
    creatorDetection: {
      detectionRisk: 'moderate',
      powerLevel: 3,
      leavesMagicalSignature: true,
      detectionNotes: 'Breath magic: Defensive command - directing awakened objects to protect',
    },
  },
  {
    id: 'breath_command_attack',
    name: 'Command: Strike',
    paradigmId: 'breath',
    technique: 'create',
    form: 'body',
    source: 'psionic',
    manaCost: 50,
    castTime: 15,
    range: 10,
    duration: 60,
    effectId: 'ignite_effect',
    description: 'Direct your Awakened creation to attack. The Command is simple; execution varies by medium. Awakened rope strangles. Awakened cloth smothers. Awakened smoke chokes. The magic interprets "strike" literally, creatively, often disturbingly. Specificity in Commands is recommended.',
    school: 'commands',
    baseMishapChance: 0.08,
    hotkeyable: true,
    icon: '⚔️',
    tags: ['breath', 'command', 'attack'],
    creatorDetection: {
      detectionRisk: 'moderate',
      powerLevel: 3,
      leavesMagicalSignature: true,
      detectionNotes: 'Breath magic: Offensive command - directing awakened objects to attack',
    },
  },
  {
    id: 'breath_command_fetch',
    name: 'Command: Fetch',
    paradigmId: 'breath',
    technique: 'enhance',
    form: 'body',
    source: 'psionic',
    manaCost: 50,
    castTime: 25,
    range: 15,
    duration: 300,
    effectId: 'heal_effect',
    description: 'Make your Awakened object retrieve something. Point. Say "Fetch." The object obeys within its capabilities. Awakened rope slithers across floors, wraps around the target item, pulls it back. Simple. Useful. Makes you feel like you\'ve trained reality itself to heel.',
    school: 'commands',
    baseMishapChance: 0.05,
    hotkeyable: true,
    icon: '🎯',
    tags: ['breath', 'command', 'utility'],
    creatorDetection: {
      detectionRisk: 'moderate',
      powerLevel: 3,
      leavesMagicalSignature: true,
      detectionNotes: 'Breath magic: Utility command - basic awakened object manipulation',
    },
  },
  {
    id: 'breath_return',
    name: 'Return Breath',
    paradigmId: 'breath',
    technique: 'enhance',
    form: 'spirit',
    source: 'psionic',
    manaCost: 0,
    castTime: 60,
    range: 1,
    effectId: 'heal_effect',
    description: 'Reclaim Breath from an Awakened object. The life drains away; the object becomes mundane again; your Breath returns intact. This is recycling on an ontological scale—no waste, just conversion. Most Awakeners treat Breath as currency, investing and recovering as needed.',
    school: 'awakening',
    baseMishapChance: 0.02,
    hotkeyable: true,
    icon: '🔄',
    tags: ['breath', 'recovery', 'utility'],
    creatorDetection: {
      detectionRisk: 'low',
      powerLevel: 2,
      leavesMagicalSignature: false,
      detectionNotes: 'Breath magic: Breath recovery - reclaiming invested life force',
    },
  },
];

// ============================================================================
// PACT PARADIGM SPELLS - Contract Magic with Otherworldly Entities
// ============================================================================

export const PACT_SPELLS: SpellDefinition[] = [
  // === Negotiation & Binding ===
  {
    id: 'pact_summon_minor',
    name: 'Call Lesser Entity',
    paradigmId: 'pact',
    technique: 'create',
    form: 'spirit',
    source: 'void',
    manaCost: 40,
    castTime: 120,
    range: 5,
    duration: 600,
    effectId: 'heal_effect',
    description: 'Reach across dimensional boundaries and summon something small. Imps are traditional. Sprites if you\'re optimistic. You offer terms—usually service for service, equivalent exchange. The entity appears, hears your proposal, accepts or vanishes. Negotiations at the cosmic scale: surprisingly bureaucratic.',
    school: 'summoning',
    baseMishapChance: 0.10,
    hotkeyable: false,
    icon: '👹',
    tags: ['pact', 'summoning', 'negotiation'],
    creatorDetection: {
      detectionRisk: 'high',
      forbiddenCategories: ['planar_travel'],
      powerLevel: 5,
      leavesMagicalSignature: true,
      detectionNotes: 'Pact magic: Entity summoning - pulling beings across planes draws scrutiny',
    },
  },
  {
    id: 'pact_seal_contract',
    name: 'Seal the Bargain',
    paradigmId: 'pact',
    technique: 'enhance',
    form: 'spirit',
    source: 'void',
    manaCost: 30,
    castTime: 60,
    range: 5,
    duration: -1,
    effectId: 'heal_effect',
    description: 'Formalize a pact with metaphysical contract. Both parties agree to terms; you invoke this spell; reality enforces compliance. Break the contract and cosmic consequences follow—automatic, impartial, often creative. This is magic as legal system: binding, bilateral, and absolutely serious.',
    school: 'binding',
    baseMishapChance: 0.08,
    hotkeyable: false,
    icon: '📜',
    tags: ['pact', 'contract', 'binding'],
    creatorDetection: {
      detectionRisk: 'moderate',
      powerLevel: 4,
      leavesMagicalSignature: true,
      detectionNotes: 'Pact magic: Contract sealing - formalizing otherworldly agreements',
    },
  },
  {
    id: 'pact_invoke_patron',
    name: 'Call Upon Patron',
    paradigmId: 'pact',
    technique: 'create',
    form: 'spirit',
    source: 'void',
    manaCost: 60,
    castTime: 40,
    range: 0,
    effectId: 'lightning_strike_effect',
    description: 'Ask your patron for direct intervention. This isn\'t prayer—it\'s contractual obligation. You\'ve paid (or are paying) for services; now you invoke them. Powerful entities respond according to agreement terms. Usually helpful. Occasionally pedantic about exact wording. Always watching the balance.',
    school: 'invocation',
    baseMishapChance: 0.12,
    hotkeyable: true,
    icon: '📞',
    tags: ['pact', 'patron', 'invocation'],
    creatorDetection: {
      detectionRisk: 'high',
      powerLevel: 6,
      leavesMagicalSignature: true,
      detectionNotes: 'Pact magic: Patron invocation - calling upon powerful entity for direct intervention',
    },
  },
  {
    id: 'pact_borrow_power',
    name: 'Borrowed Might',
    paradigmId: 'pact',
    technique: 'enhance',
    form: 'body',
    source: 'void',
    manaCost: 50,
    castTime: 30,
    range: 0,
    duration: 300,
    effectId: 'heal_effect',
    description: 'Channel your patron\'s power temporarily. For five minutes, you\'re enhanced beyond mortal limits—stronger, faster, tougher. The power is lent, not given. You\'ll return it, possibly with interest depending on contract fine print. Reading the entire pact is always recommended. Few do.',
    school: 'invocation',
    baseMishapChance: 0.14,
    hotkeyable: true,
    icon: '💪',
    tags: ['pact', 'buff', 'borrowed'],
    creatorDetection: {
      detectionRisk: 'moderate',
      powerLevel: 4,
      leavesMagicalSignature: true,
      detectionNotes: 'Pact magic: Power borrowing - channeling otherworldly might temporarily',
    },
  },
  {
    id: 'pact_mark_target',
    name: 'Mark of the Bargain',
    paradigmId: 'pact',
    technique: 'create',
    form: 'spirit',
    source: 'void',
    manaCost: 35,
    castTime: 25,
    range: 15,
    duration: 1800,
    effectId: 'heal_effect',
    description: 'Place your patron\'s mark on a target. It\'s invisible to most, but your patron (and you) always know where they are. Tracking. Targeting. Sometimes protection, sometimes threat. The mark fades after half an hour unless made permanent through additional pact terms.',
    school: 'binding',
    baseMishapChance: 0.09,
    hotkeyable: true,
    icon: '🎯',
    tags: ['pact', 'mark', 'tracking'],
    creatorDetection: {
      detectionRisk: 'moderate',
      powerLevel: 4,
      leavesMagicalSignature: true,
      detectionNotes: 'Pact magic: Mark placement - cosmic tracking visible to otherworldly eyes',
    },
  },
  {
    id: 'pact_break_deal',
    name: 'Void the Contract',
    paradigmId: 'pact',
    technique: 'enhance',
    form: 'spirit',
    source: 'void',
    manaCost: 100,
    castTime: 180,
    range: 0,
    effectId: 'heal_effect',
    description: 'Terminate a pact early. This is dangerous—breaking cosmic contracts has consequences. You\'ll pay penalties, lose benefits, possibly anger entities with long memories. But sometimes it\'s necessary. The spell severs the connection cleanly, if not kindly. Freedom has costs.',
    school: 'binding',
    baseMishapChance: 0.30,
    hotkeyable: false,
    icon: '🔓',
    tags: ['pact', 'break', 'freedom', 'risky'],
    creatorDetection: {
      detectionRisk: 'high',
      powerLevel: 5,
      leavesMagicalSignature: true,
      detectionNotes: 'Pact magic: Contract violation - breaking cosmic agreements sends ripples through reality',
    },
  },
];

