/**
 * SectorTierAdapter - Converts collections of AbstractSystem instances to AbstractSector tiers
 *
 * Aggregates star system data and creates sector-level statistics.
 */

import { AbstractSector } from '../abstraction/AbstractSector.js';
import type { AbstractSystem } from '../abstraction/AbstractSystem.js';

export interface SectorConfig {
  id: string;
  name: string;
  address: { gigasegment: number; megasegment?: number };
  galacticCoords: { x: number; y: number; z: number };
}

export class SectorTierAdapter {
  /**
   * Convert an array of AbstractSystem instances into an AbstractSector tier
   */
  static convertSystemsToSectorTier(systems: AbstractSystem[], config: SectorConfig): AbstractSector {
    if (!systems) throw new Error('systems parameter is required');
    if (!Array.isArray(systems) || systems.length === 0) throw new Error('systems array cannot be empty');

    const sector = new AbstractSector(config.id, config.name, config.address);

    // Set galactic coordinates from config
    sector.spatial.galacticCoords = config.galacticCoords;

    // Aggregate population
    const totalPopulation = systems.reduce((sum, s) => sum + s.population.total, 0);
    sector.population.total = totalPopulation;

    // Calculate max tech level
    const maxTechLevel = Math.max(...systems.map(s => s.tech.level));
    sector.tech.level = maxTechLevel;

    // Update sector stats
    sector.sectorStats.totalPopulation = totalPopulation;
    sector.sectorStats.maxTechLevel = maxTechLevel;
    sector.sectorStats.avgTechLevel = systems.reduce((sum, s) => sum + s.tech.level, 0) / systems.length;
    sector.sectorStats.spacefaringCivCount = systems.filter(s => s.tech.level >= 7).length;
    sector.sectorStats.ftlCapableCivCount = systems.filter(s => s.tech.level >= 9).length;

    // Add wormhole gates for FTL-capable systems
    if (sector.sectorStats.ftlCapableCivCount >= 2) {
      const ftlSystems = systems.filter(s => s.tech.level >= 9);
      for (let i = 0; i < ftlSystems.length - 1; i++) {
        sector.infrastructure.wormholeGates.push({
          id: `gate_${config.id}_${i}`,
          sourceSystem: ftlSystems[i]!.id,
          destinationSystem: ftlSystems[i + 1]!.id,
          distance: 10,
          travelTime: 1,
          stability: 0.95,
          operational: true,
        });
      }
    }

    // Build political entities from spacefaring systems
    // Clear any entities generated by the AbstractSector constructor since we're
    // building them properly from actual system data
    sector.politicalEntities.length = 0;
    if (systems.filter(s => s.tech.level >= 7).length > 0) {
      sector.politicalEntities.push({
        id: `${config.id}_primary_empire`,
        name: `${config.name} Hegemony`,
        type: 'empire',
        controlledSystems: systems.filter(s => s.tech.level >= 7).map(s => s.id),
        population: totalPopulation,
        techLevel: maxTechLevel,
        militaryPower: totalPopulation * 0.001,
        diplomaticStance: new Map(),
      });
    }

    // Add all systems as children
    for (const system of systems) {
      sector.addChild(system);
    }

    return sector;
  }

  /**
   * Get a resource summary for a sector
   */
  static getSectorResources(sector: AbstractSector): {
    totalPopulation: number;
    systemCount: number;
    maxTechLevel: number;
    spacefaringCount: number;
  } {
    return {
      totalPopulation: sector.population.total,
      systemCount: sector.children.length,
      maxTechLevel: sector.sectorStats.maxTechLevel,
      spacefaringCount: sector.sectorStats.spacefaringCivCount,
    };
  }
}
